- package-lock.json
This PR will fix following error with onrelase GitHub action:
> chore: rebuild package-lock.json using node version 16.15.0 and npm 8.5

- .eslintignore
- .github/workflows/publish-to-npm.yml
The publish to npm Action failed, this PR will fix the node issue
> ci: fix github action to node version with node setup

- package-lock.json
- package.json
https://github.com/UCLALibrary/design-tokens/releases/tag/v3.7.0
> feat: update ucla-library-design-tokens

- src/lib-components/Flexible/Form.vue
fix: update form css to include 
`border: 1px var(--color-primary-blue-01) solid;
border-radius: 4px;`
> fix: update form css

- dev/serve.vue
- src/lib-components/SimpleCards.vue
- src/lib-components/index.js
- src/stories/SimpleCards.spec.js
- src/stories/SimpleCards.stories.js
Connected to [APPS-1688](https://jira.library.ucla.edu/browse/APPS-1688)
Add SimpleCards
> feat: add simple cards

- .storybook/main.js
- build/rollup.config.js
- package-lock.json
- package.json
- src/lib-components/BannerText.vue
- src/lib-components/BlockEvent.vue
- src/lib-components/BlockLocationListItem.vue
- src/lib-components/MastheadPrimary.vue
- src/lib-components/RichText.vue
- vue.config.js
- updates rollup, vue-cli, and storybook configs to use postcss to resolve inline and external svg issue
> fix: update configs to use postcss

- dev/serve.vue
> fix: serve fix for siteBrandBar

- src/lib-components/HeaderSmart.vue
Connected to [APPS-1717](https://jira.library.ucla.edu/browse/APPS-1717)
**Checklist:**
> fix: headerSmart vuex state

- src/lib-components/Flexible/MediaWithText.vue
- src/lib-components/FooterPrimary.vue
- src/lib-components/FooterSock.vue
Connected to [APPS-1723](https://jira.library.ucla.edu/browse/APPS-1723)
**Component Updated:** FooterPrimary.vue and FooterSock.vue and MediaWithText.vue
**Notes:**
This PR will fix vuex state data issue in preview mode on Craft as the navigation is not setup for MEAP, Nuxtjs generate could not create static pages and preview works on client side so global data is not available.
**Checklist:**
> fix: Add else condition for vuex state data and add ::v-deep to update svg path fill color in scss

- dev/serve.vue
There were several small errors and duplications
> fix: small errors

- src/lib-components/MastheadSecondary.vue
- src/stories/MastheadSecondary.spec.js
- src/stories/MastheadSecondary.stories.js
for MastheadSecondary to appear properly in the meap site, it should include the props `theme="meap"` and `:hero-image="heroImage"`
> feat: Add MEAP theme to MastheadSecondary

- src/mixins/getParentPageTitle.js
fix: update getparentpage logic for applicants pages
> fix: update getparentpage logic

- README.md
Connected to [APPS-1676](https://jira.library.ucla.edu/browse/APPS-1676)
> feat: add readMe with tips and insights

- README.md
- src/lib-components/FooterSponsor.vue
Connected to [APPS-1754](https://jira.library.ucla.edu/browse/APPS-1754)
**Checklist:**
> fix: Footer sponsor change

- src/lib-components/BannerHeader.vue
- src/mixins/getParentPageTitle.js
- src/mixins/getSectionName.js
- src/stories/BannerHeader.stories.js
Connected to [APPS-1750](https://jira.library.ucla.edu/browse/APPS-1750)
- update wayfinder colors
- update navbreadcrumb title for project pages
- update BannerHeader hatch to only use color for current page
> fix: ux updates meap project page

- src/lib-components/HeaderSmart.vue
> fix: update isMobile

- src/stories/HeaderSmart.stories.js
Connected to [APPS-1741](https://jira.library.ucla.edu/browse/APPS-1741)
fix: state store for winWidth
> fix: state store for winWidth

- src/lib-components/BannerHeader.vue
- src/lib-components/BlockHours.vue
- src/lib-components/DividerWayFinder.vue
- src/lib-components/Flexible/Form.vue
+ BannerHeader
+ BlockHours
+ DividerWayFinder
+ FlexibleForm
> chore: ux updates 8-3-2022

- dev/serve.vue
- src/lib-components/BannerFeatured.vue
- src/lib-components/Flexible/AssociatedTopicCards.vue
- src/lib-components/Flexible/BannerFeatured.vue
- src/lib-components/IconWithLink.vue
- src/mixins/getPrompt.js
- src/stories/BannerFeatured.stories.js
- src/stories/Flexible_BannerFeatured.stories.js
Connected to [APPS-1745](https://jira.library.ucla.edu/browse/APPS-1745)
**Component Updated:** 
src/lib-components/BannerFeatured.vue
src/lib-components/Flexible/AssociatedTopicCards.vue
src/lib-components/Flexible/BannerFeatured.vue
src/lib-components/IconWithLink.vue
**Stories:** 
src/stories/BannerFeatured.stories.js
src/stories/Flexible_BannerFeatured.stories.js
**Notes:**
This will fix failing cypress tests on meap website. The styling for byline will. bee added in another ticket.
**Checklist:**
-   [ ] UX has reviewed and approved …
> feat: Flexible Banner Featured supports the new craft structure

- src/lib-components/BlockStaffDetail.vue
- src/lib-components/DividerGeneral.vue
- src/lib-components/DividerWayFinder.vue
- src/lib-components/FlexibleBlocks.vue
- src/lib-components/SectionStaffArticleList.vue
- brining over styles from the nuxt app 
- clean up comments
- remove divider-general styling from flexible-blocks and adjust padding
> chore: qa of divider-general and divider-way-finder

- src/lib-components/BlockHighlight.vue
- src/lib-components/Flexible/Highlight.vue
- src/stories/Flexible_Highlight.stories.js
fix: block and flexible highlight update
> fix: block and flexible highlight update

- package-lock.json
- package.json
- src/lib-components/BlockCallToAction.vue
- src/lib-components/BlockCallToActionTwoUp.vue
- src/lib-components/ButtonLink.vue
- src/lib-components/ButtonMore.vue
- src/lib-components/Flexible/MediaWithText.vue
- src/lib-components/FlexibleBlocks.vue
- src/lib-components/FooterPrimary.vue
- src/stories/BlockCallToAction.stories.js
- updates call to action components
- updates button link label to not wrap to a new link and icon does not shrink
- updates design tokens to latest package
- fix footer molecule svg
- 
---
* feat: qa of call to action components
* feat: updates design tokens to latest
* fix: update selector for footer svg
* fix: fix gaps and margins in cta
* feat: hide decorative icons from screenreaders
* fix: fix button-more arrow position
* fix: ignore cta fpb when zebra striping
* fix: set media with text fpb width
> feat: qa call to action components

- .storybook/preview.js
- package-lock.json
- package.json
- src/lib-components/BlockCallToAction.vue
- src/lib-components/BlockCallToActionTwoUp.vue
- vue.config.js
- this removes the font face declarations from the build process of component library. 
- fonts are included in storybook and serve so we can accurately see the components
- fonts should be included at the app/nuxt level
> fix: resolve font 404 errors

- src/lib-components/BlockHighlight.vue
changes the calculation from 3 per page to 2
> fix: update highlight component

- dev/serve.vue
- src/lib-components/BlockHighlight.vue
- src/lib-components/Flexible/CardWithImage.vue
- src/stories/Flexible_CardWithImage.stories.js
Connected to [APPS-1746](https://jira.library.ucla.edu/browse/APPS-1746)
fix: card with image updates to match craft structure
> feat: card with image updates to match craft structure

- dev/serve.vue
- src/lib-components/FooterMain.vue
- src/lib-components/FooterPrimary.vue
- src/lib-components/FooterSock.vue
- src/lib-components/FooterSponsor.vue
- src/store/index.js
- src/store/modules/footerSponsor.js
- src/stories/FooterMain.stories.js
Connected to [APPS-1778](https://jira.library.ucla.edu/browse/APPS-1778)
Changes to be committed:
modified:
+ `dev/serve.vue`
+ `src/lib-components/FooterMain.vue`
+ `src/lib-components/FooterPrimary.vue`
+ `src/lib-components/FooterSock.vue`
+ `src/lib-components/FooterSponsor.vue`
+ `src/store/index.js`
+ `src/stories/FooterMain.stories.js`
+ `src/stories/FooterSponsor.stories.js`
> feat: refactor the footer elements

- src/lib-components/BlockHighlight.vue
Connected to [APPS-1808](https://jira.library.ucla.edu/browse/APPS-1808)
> fix: undo change to blockhighlight max-width

- src/lib-components/BannerFeatured.vue
- src/lib-components/BannerText.vue
- small pr to fix the wayfinder color for banner-featured to be inherited into the heading arrow component
> fix: pass wayfinder color from banner-featured to heading-arrow

- src/lib-components/BlockCallToAction.vue
- src/stories/BlockCallToAction.stories.js
Connected to [APPS-1789](https://jira.library.ucla.edu/browse/APPS-1789)
feat: meap cta variant
> feat: meap cta variant

- src/lib-components/BannerHeader.vue
- src/lib-components/SectionTeaserHighlight.vue
- src/stories/BannerHeader.stories.js
Adjust props to work with data from Meap News index
> chore: News index updates to BannerHeader and SectionTeaserHighlight

- src/lib-components/BlockSponsor.vue
- src/lib-components/FooterSponsor.vue
fixes Flexbox params and replaces <ResponsiveImage> with <img> tag to solve an issue with too-large sizer div
> fix: Sponsor footer layout

- src/lib-components/Flexible/SimpleCards.vue
- src/stories/mock/Flexible_SimpleCards.js
Connected to [APPS-1859](https://jira.library.ucla.edu/browse/APPS-1859)
fix: Simple cards data manipulation
> fix: Simple cards data manipulation

- src/lib-components/BannerText.vue
Connected to [UX-694](https://jira.library.ucla.edu/browse/UX-694)
udpates BannerText spacing
**Checklist:**
> fix: udpates BannerText spacing

- src/lib-components/NavBreadcrumb.vue
- src/mixins/getMeapParentPageTitle.js
- src/mixins/getParentPageTitle.js
- src/mixins/getParentPageUrl.js
Connected to [APPS-1828](https://jira.library.ucla.edu/browse/APPS-1828)
fix: QA navbreadcrumb
> fix: QA navbreadcrumb

- src/lib-components/BlockCallToAction.vue
- src/lib-components/BlockHighlight.vue
- src/lib-components/Flexible/CardWithImage.vue
- src/lib-components/Flexible/Highlight.vue
Misc QA for responsive styling bugs
**Checklist:**
> fix: responsive styling for BlockHiglight, CTA, CardWithImage, 

- src/lib-components/FooterSponsor.vue
Connected to [APPS-1855](https://jira.library.ucla.edu/browse/APPS-1855)
updates FooterSponsor spacing
> fix: updates FooterSponsor spacing

- src/lib-components/BlockStaffArticleList.vue
Connected to [APPS-1877](https://jira.library.ucla.edu/browse/APPS-1877)
+ /about/news
---
> fix: APPS-1877 update block staff article item

- src/lib-components/FooterMain.vue
- src/lib-components/FooterPrimary.vue
- src/lib-components/NavSecondary.vue
- src/stories/FooterPrimary.stories.js
Connected to [APPS-1890](https://jira.library.ucla.edu/browse/APPS-1890)
**Component/stories/spec Created/Updated:**
modified:   src/lib-components/FooterMain.vue
modified:   src/lib-components/FooterPrimary.vue
modified:   src/lib-components/NavSecondary.vue
modified:   src/stories/FooterPrimary.stories.js
**Notes:**
Refactor footer-main later.  ucla library logo bug fixed
**Checklist:**
- …
> fix: APPS-1890 ucla library logo bug fixed

- src/lib-components/BlockStaffArticleList.vue
- src/lib-components/Flexible/SimpleCards.vue
- src/stories/BlockStaffArticleList.stories.js
- src/stories/Flexible_SimpleCards.stories.js
- src/stories/mock/Flexible_SimpleCards.js
fix: Apps 1849 update simple cards with internal and external handle for main craft simple card flexible page block
> fix: Apps 1849 update simple cards

- src/mixins/getParentPageTitle.js
Connected to [APPS-1910](https://jira.library.ucla.edu/browse/APPS-1910)
> fix: add blog to breadcrumb

- src/lib-components/BannerHeader.vue
move text above byline and location
> fix: move text

- dev/serve.vue
- src/lib-components/Flexible/CardWithImage.vue
- src/lib-components/Flexible/GridGalleryCards.vue
- src/lib-components/Flexible/Highlight.vue
- src/lib-components/FlexibleBlocks.vue
- src/lib-components/FooterSponsor.vue
- src/lib-components/GridGallery.vue
- src/lib-components/NavPrimary.vue
- src/lib-components/index.js
- src/mixins/getPrompt.js
- src/stories/Flexible_BannerFeatured.stories.js
- src/stories/Flexible_GridGalleryCards.spec.js
- src/stories/Flexible_GridGalleryCards.stories.js
Connected to [APPS-1902](https://jira.library.ucla.edu/browse/APPS-1902)
modified:   dev/serve.vue
modified:   src/lib-components/Flexible/CardWithImage.vue
modified:   src/lib-components/Flexible/Highlight.vue
modified:   src/lib-components/FlexibleBlocks.vue
modified:   src/lib-components/FooterSponsor.vue
modified:   src/lib-components/GridGallery.vue
modified:   src/lib-components/NavPrimary.vue
modified:   src/lib-components/index.js
src/lib-components/Flexible/GridGalleryCards.vue
src/stories/Flexible_GridGalleryCards.spec.js
src/stories/Flexible_GridGalleryCards.stories.js
**Notes:**
Update prompt mixin and Create Flexible_GridGalleryCards component
**Checklist:**
-   [x] I checked that it is working locally in the …
> feat: Update prompt mixin and Create Flexible_GridGalleryCards component

- src/lib-components/BlockStaffDetail.vue
Connected to [UX-599](https://jira.library.ucla.edu/browse/UX-599)
- standardizes to existing conventions via spacing tokens
- standardizes desktop width and chevron display
- resolves issue of pronoun display
- adds divider-way-finder between Ask Me About and Biography sections with conditional logic
**Checklist:**
> fix: updates BlockStaffDetail spacing

- dev/serve.vue
- src/lib-components/Flexible/BannerFeatured.vue
- src/lib-components/Flexible/CardWithImage.vue
- src/lib-components/Flexible/Highlight.vue
- src/stories/Flexible_BannerFeatured.stories.js
- src/stories/mock/Flexible_CardWithImage.js
- src/stories/mock/Flexible_Highlight.js
Connected to [APPS-1938](https://jira.library.ucla.edu/browse/APPS-1938)
> fix: impact report video, card with image and highlight

- src/lib-components/BlockForm.vue
- src/mixins/isInternalLink.js
- src/stories/BlockForm.stories.js
Connected to [APPS-1907](https://jira.library.ucla.edu/browse/APPS-1907)
**Stories:** ~/stories/BlockForm.stories.js
**Checklist:**
> feat: Apps 1907 block form style

- src/lib-components/BannerText.vue
- src/stories/BannerText.stories.js
Connected to [APPS-1510](https://jira.library.ucla.edu/browse/APPS-1510)
> fix: byline on banner text

- src/lib-components/SectionWrapper.vue
Connected to [APPS-1988](https://jira.library.ucla.edu/browse/APPS-1988)
needed for the banner-header styling
> chore: sectionWrapper for the banner-header

- dev/serve.vue
- src/lib-components/BaseCheckboxGroup.vue
- src/lib-components/BaseRadioGroup.vue
- src/lib-components/SearchGeneric.vue
- src/lib-components/SearchGenericFilterButtons.vue
- src/stories/SearchGeneric.stories.js
Connected to [APPS-877](https://jira.library.ucla.edu/browse/APPS-877)
**Component Update:** SearchGeneric.vue, BaseCheckboxGroup and BaseRadioGroup
**Stories:** ~/stories/SearchGeneric.stories.js
**Notes:**
Added v-deep to make the svg class changes visible on nuxt page.
updated sync modifier on the selected prop.
**Checklist:**
> fix: APPS-877 update search-generic component to sync filters

- src/lib-components/BlockForm.vue
**Component Created:** BlockForm.vue
**Notes:**
When connected with Nuxtjs scrape id, the email required needed to be checked later in the code.
Once merged, needs a component version updated on the nuxt side
> fix: add check for email required later in the lifecycle

- src/lib-components/FlexibleBlocks.vue
- src/lib-components/SearchGeneric.vue
Connected to [APPS-2010](https://jira.library.ucla.edu/browse/APPS-2010)
**Notes:**
Fix transitions for drop downs and add z-index
**Checklist:**
> fix: APPS-2010

- src/lib-components/BannerHeader.vue
- src/lib-components/BannerText.vue
- src/lib-components/BlockStaffArticleList.vue
- src/stories/BannerHeader.stories.js
- src/stories/BannerText.stories.js
Connected to [APPS-1947](https://jira.library.ucla.edu/browse/APPS-1947)
This PR 
+ updates the conditionals and the CSS Styling of the BannerText & BannerHeader
+ changes the color of the Category on the Article List Component
+ updates the stories for the byline to be consistent
> feat: Add subject area to banner text and header

- src/lib-components/SearchHome.vue
Connected to [APPS-2039](https://jira.library.ucla.edu/browse/APPS-2039)
fix: update searchhome
> fix: update searchhome

- src/lib-components/BannerFeatured.vue
- src/lib-components/BannerHeader.vue
- src/lib-components/BannerText.vue
- src/lib-components/BlockHighlight.vue
- src/lib-components/BlockStaffDetail.vue
- src/lib-components/DividerWayFinder.vue
- updates default color in hatch lines
- removes margin-bottom on banner* components that don't have a form
- adds altname and lang back to staff detail 
**Checklist:**
> feat: updates recent bugs and QA

- src/lib-components/BlockEvent.vue
- src/lib-components/BlockHighlight.vue
- src/lib-components/BlockLocationListItem.vue
- src/lib-components/BlockPostSmall.vue
- src/lib-components/BlockStaffArticleList.vue
- src/lib-components/BlockStaffList.vue
- src/lib-components/FooterPrimary.vue
- src/lib-components/HeaderMainResponsive.vue
- src/lib-components/NavBreadcrumb.vue
- src/lib-components/NavPrimary.vue
- src/lib-components/SectionCardsWithIllustrations.vue
- src/lib-components/SectionDualMasonry.vue
- src/lib-components/SectionPagination.vue
- src/lib-components/SectionPostSmall.vue
> fix: update all router-links  to smart-links

- src/lib-components/Flexible/MediaGallery.vue
- src/lib-components/Flexible/MediaGallery/BannerImage.vue
> fix: support embeds in MediaGalleryBannerImage

- src/lib-components/Flexible/CardWithImage.vue
- src/lib-components/Flexible/Highlight.vue
Connected to [APPS-2065](https://jira.library.ucla.edu/browse/APPS-2065)
> fix: update fpbs for images

- src/lib-components/BlockGenericList.vue
- src/lib-components/FlexibleBlocks.vue
- src/stories/BlockGenericList.spec.js
- src/stories/BlockGenericList.stories.js
> feat: APPS-2073 added spec file storybook file and component file

- src/lib-components/SearchGeneric.vue
Connected to [APPS-1977](https://jira.library.ucla.edu/browse/APPS-1977)
**Notes:**
> fix: Move search icon to right of the input text and add hover behavior

- src/lib-components/SearchHome.vue
Connected to [APPS-2046](https://jira.library.ucla.edu/browse/APPS-2046)
> fix: rename search_site to search-site

- src/lib-components/BannerFeatured.vue
- src/lib-components/BlockGenericList.vue
- src/lib-components/BlockHighlight.vue
- src/lib-components/BlockStaffDetail.vue
> fix: prefix location link with forward slash

- src/lib-components/SearchGeneric.vue
This PR will fix, issues with opening and closing filter drop downs, and form will be submitted once after the user clicks the search icon and when the user clicks enter on the input text.
> fix: Fix search generic

- src/lib-components/BlockGenericList.vue
- src/lib-components/SectionGenericList.vue
- src/stories/SectionGenericList.stories.js
Add payRate to GenericList & Fix styling
> fix: add payRate to GenericList

- src/lib-components/BannerFeatured.vue
Connected to [APPS-2080](https://jira.library.ucla.edu/browse/APPS-2080)
> fix: APPS-2080 Link title on the bannerFeatured component

- src/lib-components/BlockShowHide.vue
- src/lib-components/ButtonHide.vue
- src/lib-components/ButtonShow.vue
- src/lib-components/SectionSpacesList.vue
- src/lib-components/SectionTeaserList.vue
- src/stories/BlockShowHide.spec.js
- src/stories/BlockShowHide.stories.js
- src/stories/ButtonHide.spec.js
- src/stories/ButtonHide.stories.js
- src/stories/ButtonShow.spec.js
- src/stories/ButtonShow.stories.js
- src/stories/SectionSpacesList.spec.js
- src/stories/SectionSpacesList.stories.js
- src/stories/SectionTeaserList.spec.js
- src/stories/SectionTeaserList.stories.js
> feat: ShowHide component

- src/lib-components/BlockLocationListItem.vue
- src/lib-components/BlockStaffList.vue
- src/lib-components/SectionLocationList.vue
- src/stories/Flexible_Form.spec.js
Updates location listing cards 
https://deploy-preview-273--ucla-library-storybook.netlify.app/?path=/story/section-location-list--default
> feat: location listing component qa

- src/lib-components/ButtonLink.vue
- src/lib-components/SiteNotificationAlert.vue
- src/lib-components/SmartLink.vue
- src/stories/ButtonLink.stories.js
QA issues and styling, plus a refactor of css transitions to animate the clip-path property
> refactor: improvements and fixes to ButtonLink and SiteNotificationAlert

- .github/workflows/ci.yml
- .github/workflows/percy.yml
- .github/workflows/publish-to-npm.yml
- .github/workflows/setup-workspace/action.yml
- src/lib-components/BannerText.vue
- src/lib-components/BlockGenericList.vue
- src/lib-components/BlockHighlight.vue
- src/stories/BannerText.stories.js
- src/stories/BlockGenericList.stories.js
- src/stories/BlockHighlight.stories.js
- adds alternative name and language to banner-text, block-generic-list, and block-highlight
> feat: add alternativeName to generic list and highlight components

- src/lib-components/SectionGenericList.vue
- src/lib-components/SectionTeaserHighlight.vue
- adds alternativeName and language to section-generic-list and section-teaser-highlight
> fix: add alternativeName and language to sections

- src/lib-components/BlockCardWithIllustration.vue
- src/lib-components/SearchHome.vue
- src/mixins/removeHtmlTruncate.js
- src/stories/BlockCardWithIllustration.stories.js
Connected to [APPS-2145](https://jira.library.ucla.edu/browse/APPS-2145)
https://deploy-preview-295--ucla-library-storybook.netlify.app/?path=/story/block-card-with-illustration--default
https://deploy-preview-295--ucla-library-storybook.netlify.app/?path=/story/search-search-home--default
> fix: Fix html tag display on cards-with-illustration

- src/lib-components/SectionTeaserCard.vue
Fixes issue in Endowments Listing > Featured Endowments
> fix: SectionTeaserCard alternativeName

- src/stories/mock/Flexible_CallToAction.js
Fixes mock data to match expected format
> fix: link URL in BlockCallToAction

- src/lib-components/BlockCardWithIllustration.vue
- src/mixins/removeHtmlTruncate.js
> fix: revert null check

- .env
- .gitignore
- src/lib-components/BlockAmenities.vue
Connected to [APPS-2141](https://jira.library.ucla.edu/browse/APPS-2141))
> fix: APPS-2141 Fix print svg and text in Block Amenities

- src/lib-components/BlockStaffList.vue
- src/lib-components/BlockStaffSubjectLibrarian.vue
- src/lib-components/FooterPrimary.vue
- src/lib-components/SearchGeneric.vue
- src/lib-components/SearchGenericFilterButtons.vue
- src/lib-components/SectionStaffSubjectLibrarian.vue
Connected to [APPS-2118](https://jira.library.ucla.edu/browse/APPS-2118)
Going forward we should first check if certain html elements should be nested inside another html elemenets and use v-html sparingly, only use if there is raw html in the text
> fix: hydration errors

- src/lib-components/SearchGeneric.vue
Reverts UCLALibrary/ucla-library-website-components#308
> Revert "fix: Add remove filters back"

- src/lib-components/SearchGeneric.vue
SectionRemovesearchfilters is problematic so adding this back
> fix: Add click-outside directive back

- src/lib-components/Flexible/BannerFeatured.vue
- src/lib-components/Flexible/CardWithImage.vue
- src/lib-components/Flexible/Highlight.vue
- src/stories/Flexible_BannerFeatured.stories.js
- src/stories/Flexible_CardWithImage.stories.js
- src/stories/Flexible_Highlight.stories.js
- src/stories/mock/Flexible_Highlight.js
Connected to [APPS-2021](https://jira.library.ucla.edu/browse/APPS-2021) and [APPS-2009](https://jira.library.ucla.edu/browse/APPS-2009)
Flexible Banner Featured https://deploy-preview-312--ucla-library-storybook.netlify.app/?path=/story/flexible-banner-featured--event
Flexible Card With Image https://deploy-preview-312--ucla-library-storybook.netlify.app/?path=/story/flexible-card-with-image--event-exhibiton-article
Flexible Highlight https://deploy-preview-312--ucla-library-storybook.netlify.app/?path=/story/flexible-highlight--event-exhibiton-article
> fix: Refactor date time for flexible_Banner* components and Fix category null display in BlockHighlight

- src/lib-components/BlockHighlight.vue
- src/lib-components/Flexible/CardWithImage.vue
- src/lib-components/Flexible/Highlight.vue
- src/lib-components/SectionTeaserCard.vue
- src/lib-components/SectionTeaserHighlight.vue
- src/lib-components/SectionTeaserList.vue
- src/stories/BlockHighlight.stories.js
- src/stories/SectionTeaserHighlight.stories.js
- src/stories/SectionTeaserList.stories.js
adds ongoing prop and removes date clip for block highlight list to improve display on exhibitions and series https://deploy-preview-311--ucla-library-storybook.netlify.app/?path=/story/block-highlight--list-ongoing
> feat: add ongoing prop to block highlight

- src/lib-components/SearchGeneric.vue
- src/lib-components/SectionRemoveSearchFilter.vue
- src/mixins/removeHtmlTruncate.js
- src/mixins/stripCraftURLFromText.js
Connected to [APPS-2123](https://jira.library.ucla.edu/browse/APPS-2123), [APPS-2140](https://jira.library.ucla.edu/browse/APPS-2140),[APPS-2163](https://jira.library.ucla.edu/browse/APPS-2163)
> fix: remove v-if to v-show and add null check and use replace all

- src/lib-components/FooterPrimary.vue
https://deploy-preview-324--ucla-library-storybook.netlify.app/?path=/story/footer-primary--default
> feat: add subscription code for mailing list in footer

- src/lib-components/BlockStaffDetail.vue
- src/stories/BlockStaffDetail.stories.js
Connected to [APPS-2153](https://jira.library.ucla.edu/browse/APPS-2153)
https://deploy-preview-325--ucla-library-storybook.netlify.app/?path=/story/block-staff-detail--default 
- displays departments on separate lines
- adjusts line height for job title
> feat: updates BlockStaffDetail styling

- src/lib-components/Flexible/MediaGallery.vue
- src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
- src/stories/Flexible_MediaGallery.spec.js
- src/stories/mock/Media.js
Connected to [APPS-2156](https://jira.library.ucla.edu/browse/APPS-2156)
> fix: ThumbnailCard link, and credit if no caption

- src/lib-components/BlockStaffDetail.vue
- src/stories/BlockStaffDetail.spec.js
- src/stories/BlockStaffDetail.stories.js
Before:
After (local nuxt linked to rebuilt component):
> fix: raw json in staff detail > department field

- src/lib-components/SearchGeneric.vue
- src/lib-components/SearchHome.vue
- src/stories/SearchGeneric.stories.js
Connected to [APPS-2142](https://jira.library.ucla.edu/browse/APPS-2142)
https://deploy-preview-332--ucla-library-storybook.netlify.app/?path=/story/search-search-home--default
> feat: APPS-2142 Update Search components placeholders

- src/lib-components/SectionStaffSubjectLibrarian.vue
Connected to [APPS-2165](https://jira.library.ucla.edu/browse/APPS-2165)
> fix: APPS-2165 Update Contact a Subject Librarian section to include caption in table

- src/lib-components/AlphabeticalBrowseBy.vue
Connected to [APPS-2100](https://jira.library.ucla.edu/browse/APPS-2100)
add `.title @include step-3`
> fix: APPS-2100_update-browse-by-default-state

- src/lib-components/RichText.vue
Connected to [APPS-1920](https://jira.library.ucla.edu/browse/APPS-1920)
- scales icon-external down to be inline with step-0 body font size
- lessens space between link and icon
> fix: external link styling

- src/lib-components/BlockStaffArticleList.vue
- src/stories/BlockStaffArticleList.stories.js
Connected to [APPS-2161](https://jira.library.ucla.edu/browse/APPS-2161)
> fix: APPS-2161 Update maxlength for block-staff-article-list on Program index

- src/stories/mock/Flexible_MediaWithText.js
Connected to [APPS-2086](https://jira.library.ucla.edu/browse/APPS-2086)
> fix: Add audio and vidoe embed code to flexible media with text stories mock data.

- src/lib-components/BaseCheckboxGroup.vue
- src/lib-components/BaseRadioGroup.vue
- src/lib-components/SearchGeneric.vue
- src/lib-components/SearchGenericFilterButtons.vue
- src/lib-components/SingleCheckbox.vue
Connected to [APPS-2117](https://jira.library.ucla.edu/browse/APPS-2117)
updates search generic filter button styling for tablet and mobile
https://deploy-preview-343--ucla-library-storybook.netlify.app/?path=/story/search-generic--default
> feat: update search filter responsive styling

- src/lib-components/SearchInput.vue
fixing nuxt errors on component version update
> fix: remove search-input scoped slots not supported by nuxt2

- src/lib-components/SearchGeneric.vue
Connected to [APPS-2375](https://jira.library.ucla.edu/browse/APPS-2375)
> fix: add support for enter key for searching

- ucla-library-website-components-vue3.x/package-lock.json
- ucla-library-website-components-vue3.x/package.json
> chore: add lint script and eslint packages for vue and cypress

- ucla-library-website-components-vue3.x/package-lock.json
- ucla-library-website-components-vue3.x/package.json
> chore: add cypress

- ucla-library-website-components-vue3.x/package.json
add vue to peer dependencies as it is going to be used a s library in other vue /nuxt projects
> chore: add vue to peer dependencies

- ucla-library-website-components-vue3.x/package.json
set engine in package.json to use specific node and npm version
> chore: add node and npm version to package.json

- ucla-library-website-components-vue3.x/.eslintrc.cjs
- ucla-library-website-components-vue3.x/package-lock.json
- ucla-library-website-components-vue3.x/package.json
- ucla-library-website-components-vue3.x/tsconfig.json
Add eslint and use airbnb style guide
> chore: Add eslint

- ucla-library-website-components-vue3.x/.prettierrc.cjs
- ucla-library-website-components-vue3.x/package-lock.json
- ucla-library-website-components-vue3.x/package.json
- ucla-library-website-components-vue3.x/src/App.vue
- ucla-library-website-components-vue3.x/src/components/HelloWorld.vue
- ucla-library-website-components-vue3.x/src/main.ts
Add prettier, and scripts to lint and format code, need to add vue setting for vscode to use volar as default formatter
> chore: Add prettier

- src/lib-components/SearchHome.vue
Connected to [APPS-2386](https://jira.library.ucla.edu/browse/APPS-2386)
> fix: add keyup event handler to search home

- src/lib-components/BannerHeader.vue
Connected to [APPS-2367](https://jira.library.ucla.edu/browse/APPS-2367)
> fix: APPS-2367 Lighten shadow overlay

- src/lib-components/SectionWrapper.vue
- src/stories/SectionWrapper.spec.js
- src/stories/SectionWrapper.stories.js
Connected to [APPS-2338](https://jira.library.ucla.edu/browse/APPS-2338) && [APPS-2319](https://jira.library.ucla.edu/browse/APPS-2319)
https://deploy-preview-370--ucla-library-storybook.netlify.app/?path=/story/section-wrapper--default
> fix: update - change section summary to richtext in section wrapper

- dev/index.html
- dev/serve.js
- dev/serve.vue
- package.json
- vite.config.serve.ts
Connected to [APPS-2391](https://jira.library.ucla.edu/browse/APPS-2391)
> chore: Add dev server to use component library as a plugin

- package-lock.json
- package.json
Connected to [APPS-2392](https://jira.library.ucla.edu/browse/APPS-2392)
I am updating the design component here before I update the component library version on the meap repo
> fix: APPS-2392 update design token

- .github/workflows/publish-to-npm.yml
- package.json
- release.config.js
Connected to [APPS-2409](https://jira.library.ucla.edu/browse/APPS-2409)
> ci: APPS-2409 npm next release

- package.json
Connected to [APPS-2409](https://jira.library.ucla.edu/browse/APPS-2409)
> chore: fix package.json name

- pnpm-lock.yaml
Connected to [APPS-2409](https://jira.library.ucla.edu/browse/APPS-2409)
> fix: if package.json changes run pnpm install

- README.md
Connected to [APPS-2409](https://jira.library.ucla.edu/browse/APPS-2409)
> fix: build a new version for next release candidate

- .github/workflows/ci.yml
- .github/workflows/percy.yml
> fix: ci workflows, test npm release

- README.md
> feat: test minor bump with semantic pre release alpha

- src/lib-components/Flexible/MediaGallery.vue
- src/lib-components/Flexible/MediaGallery/BannerImage.vue
- src/lib-components/FlexibleBlocks.vue
- src/lib-components/SearchGeneric.vue
- src/lib-components/SectionWrapper.vue
- src/stories/FlexibleBlocks.stories.js
- src/stories/Flexible_MediaGallery.stories.js
- src/stories/MediaGallery.spec.js
- src/stories/mock/Media.js
Connected to [APPS-1932](https://uclalibrary.atlassian.net/jira/software/c/projects/APPS/boards/12?selectedIssue=APPS-1932)
Continued from work done by [PR 393](Matteus https://github.com/UCLALibrary/ucla-library-website-components/pull/393) (Closed this PR and started a fresh branch)
[APPS-1932]: https://uclalibrary.atlassian.net/browse/APPS-1932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-1932 create media gallery half width

- src/lib-components/BannerFeatured.vue
- src/lib-components/BannerHeader.vue
- src/lib-components/BlockCallToActionTwoUp.vue
- src/lib-components/CardMeta.vue
- src/lib-components/MastheadPrimary.vue
- src/lib-components/NavMenuItem.vue
- src/lib-components/NavMenuItemResponsive.vue
- src/lib-components/NavMenuItemScriptSetup.vue
- src/lib-components/SingleCheckbox.vue
- src/lib-components/index.js
- src/stories/BannerHeader.spec.js
- src/stories/BannerHeader.stories.js
- src/stories/mock/BlockFormData.json
- src/types/types.ts
Connected to [APPS-2467](https://jira.library.ucla.edu/browse/APPS-2467)
**Component Created:** BannerHeader.vue
**Stories:** ~/stories/BannerHeader.stories.js
**Spec:** ~/stories/BannerHeader.spec.js
**Notes:**
- Component uses two components that have not yet been migrated: ResponsiveVideo and BlockForm; they will be added in subsequent tickets:
- https://uclalibrary.atlassian.net/browse/APPS-2507
- https://uclalibrary.atlassian.net/browse/APPS-2518 
**Checklist:**
-   [x] I assigned this PR to …
> feat: APPS-2467 BannerHeader component

- .github/workflows/publish-to-npm.yml
> fix: ci npm publish add node version setup for node version 20

- src/lib-components/BlockHighlight.vue
- src/stories/BlockHighlight.stories.js
- src/stories/mock/Flexible_Highlight.js
Connected to [APPS-2493](https://jira.library.ucla.edu/browse/APPS-2493)
ucla-library-website-components linked to library-website-nuxt (the highlight component is at the bottom of the page:)
http://192.168.1.205:3000/about/policies/only-cats-allowed
[APPS-2493]: https://uclalibrary.atlassian.net/browse/APPS-2493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2493 Hyperlink styling needed in FPB Highlight summary field

- src/lib-components/BlockCardWithImage.vue
- src/lib-components/BlockClippedDate.vue
- src/lib-components/BlockFloatingHighlight.vue
- src/lib-components/DividerWayFinder.vue
- src/stories/SectionTeaserHighlight.stories.js
Connected to [APPS-2411](https://jira.library.ucla.edu/browse/APPS-2411)
[APPS-2411]: https://uclalibrary.atlassian.net/browse/APPS-2411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2411 fix section name with color-default, since route path is undefined

- .eslintrc
- src/lib-components/BlockClippedDate.vue
- src/lib-components/BlockFloatingHighlight.vue
- src/lib-components/BlockRemoveSearchFilter.vue
- src/lib-components/DividerWayFinder.vue
Connected to [APPS-2411](https://jira.library.ucla.edu/browse/APPS-2411)
home page gives undefined error when dding section-teaser-floating-highlight
[APPS-2411]: https://uclalibrary.atlassian.net/browse/APPS-2411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix useroute

- src/lib-components/BlockClippedDate.vue
- src/lib-components/BlockFloatingHighlight.vue
- src/lib-components/BlockRemoveSearchFilter.vue
- src/lib-components/DividerWayFinder.vue
Connected to [APPS-2411](https://jira.library.ucla.edu/browse/APPS-2411)
[APPS-2411]: https://uclalibrary.atlassian.net/browse/APPS-2411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove duplicate color which was causing hydration error

- src/lib-components/CardMeta.vue
- src/lib-components/NavPrimary.vue
Connected to [APPS-2411](https://jira.library.ucla.edu/browse/APPS-2411)
[APPS-2411]: https://uclalibrary.atlassian.net/browse/APPS-2411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: check if route exists in cardmeta and navprimary

- package.json
- pnpm-lock.yaml
- src/lib-components/SectionWrapper.vue
Connected to [APPS-2474](https://uclalibrary.atlassian.net/jira/software/c/projects/APPS/boards/12?selectedIssue=APPS-2474))
[APPS-2474]: https://uclalibrary.atlassian.net/browse/APPS-2474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: APPS-2474 accessibility fixes

- package.json
- pnpm-lock.yaml
- src/lib-components/BlockClippedDate.vue
- src/lib-components/BlockFloatingHighlight.vue
- src/lib-components/Flexible/Highlight.vue
- src/lib-components/Flexible/MediaGallery.vue
- src/lib-components/Flexible/MediaGallery/BannerImage.vue
- src/lib-components/Flexible/MediaGallery/NewLightbox.vue
- src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
- src/lib-components/index.js
- src/stories/Flexible_MediaGallery.spec.js
- src/stories/Flexible_MediaGallery.stories.js
- src/stories/MediaGallery_NewLightbox.spec.js
- src/stories/MediaGallery_NewLightbox.stories.js
- src/types/flexible_types.ts
Connected to [APPS-2560](https://jira.library.ucla.edu/browse/APPS-2560)
**Component Created:** /Flexible/MediaGallery.vue
**Stories:** 
~/stories/Flexible_MediaGallery.stories.js
~/stories/MediaGallery_NewLightbox.stories.js
**Spec:** 
~/stories/Flexible_MediaGallery.spec.js
~/stories/MediaGallery_NewLightbox.spec.js
**Notes:**
Refactor NewLightbox component with Vue3 Carousel plugin:
https://ismail9k.github.io/vue3-carousel/
**Checklist:**
-   [x] I assigned this PR to someone on the dev team to …
> feat: APPS-2560 Add FlexibleMediaGallery + Vue3 Carousel

- src/lib-components/BaseCheckboxGroup.vue
- src/lib-components/BaseRadioGroup.vue
- src/stories/BaseCheckboxGroup.spec.js
- src/stories/BaseCheckboxGroup.stories.js
- src/stories/BaseRadioGroup.spec.js
- src/stories/BaseRadioGroup.stories.js
Connected to [APPS-2617](https://jira.library.ucla.edu/browse/APPS-2617)
**Component Created:** BaseRadioGroup.vue
**Stories:** ~/stories/BaseRadioGroup.stories.js
**Spec:** ~/stories/BaseRadioGroup.spec.js
**Component Created:** BaseCheckboxGroup.vue
**Stories:** ~/stories/BaseCheckboxGroup.stories.js
**Spec:** ~/stories/BaseCheckboxGroup.spec.js
**Notes:**
commented the watcher code as it may not be needed, will know once I work on search-generic filter buttons
**Checklist:**
-   [ ] I assigned …
> feat: Add BaseRadioGroup and BaseCheckboxGroup components to vue3 and stories are new

- src/lib-components/BlockCardWithIllustration.vue
- src/lib-components/BlockHours.vue
- src/lib-components/BlockLocationListItem.vue
- src/lib-components/BlockMediaWithText.vue
- src/lib-components/SectionWrapper.vue
Connected to [APPS-2401](https://jira.library.ucla.edu/browse/APPS-2401)
[APPS-2401]: https://uclalibrary.atlassian.net/browse/APPS-2401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: section wrapper for prerender

- src/lib-components/Flexible/BannerFeatured.vue
- src/stories/FlexibleBlocks.stories.js
- src/stories/Flexible_BannerFeatured.stories.js
- src/stories/mock/Flexible_Banner.js
Connected to [APPS-2648](https://jira.library.ucla.edu/browse/APPS-2648)
**Notes:**
- Add checks when parsing bylines in FlexibleBannerFeatured to determine if byline arrays exist
- Added test banner data to "divider-between-white-block" FlexibleBlock story
**Checklist:**
[APPS-2648]: https://uclalibrary.atlassian.net/browse/APPS-2648?atlOrigin=eyJpIjoiNWRk …
> fix: APPS-2648 Fix BannerFeatured error in FlexibleBlock component

- src/lib-components/SearchGenericFilters.vue
Connected to [APPS-2669](https://jira.library.ucla.edu/browse/APPS-2669)
The checkbox state was not updating if URL is bookmarked on nuxt3 page
[APPS-2669]: https://uclalibrary.atlassian.net/browse/APPS-2669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: search generic checkbox state 

- package.json
- pnpm-lock.yaml
- src/lib-components/BannerFeatured.vue
- src/lib-components/Flexible/BannerFeatured.vue
- src/stories/Flexible_BannerFeatured.stories.js
- src/types/flexible_types.ts
Connected to 
+ [APPS-2671](https://jira.library.ucla.edu/browse/APPS-2671) BannerFeatured digital eyebrow / category is not appearing
+ [APPS-2672](https://jira.library.ucla.edu/browse/APPS-2671) Add content type as eyebrow in Card with Image FPB for internal content
+ [APPS-2718](https://jira.library.ucla.edu/browse/APPS-2718) fix: breadcrumb on Article with Video in the Banner Featured FPB
+ [APPS-2719](https://jira.library.ucla.edu/browse/APPS-2719) fix: Left & Right Alignment on the Banner Featured FPB
https://deploy-preview-513--ucla-library-storybook-vue3x.netlify.app/?path=/docs/flexible-banner-featured--docs
+ The design system is updated in this PR
```
src/lib-components/Flexible/BannerFeatured.vue(92,62): error TS2339: Property 'workshopOrEventSeriesType' does not exist on type …
```
> fix: APPS-2671 BannerFeatured digital eyebrow / category is not appearing

- src/lib-components/FooterSponsor.vue
Connected to [APPS-2738](https://jira.library.ucla.edu/browse/APPS-2738)
**Component updated:** footerSponsor.vue
**Notes:**
To resolve active pinia not installed, convert script setup to options api
[APPS-2738]: https://uclalibrary.atlassian.net/browse/APPS-2738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-2738 convert script setup to options api

- src/lib-components/DividerWayFinder.vue
- src/stories/FlexibleBlocks.stories.js
Connected to [APPS-2794](https://jira.library.ucla.edu/browse/APPS-2794)
[APPS-2794]: https://uclalibrary.atlassian.net/browse/APPS-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add console.log to divider component to test issue on the website

- src/lib-components/DividerWayFinder.vue
- vite.config.ts
Connected to [APPS-2794](https://jira.library.ucla.edu/browse/APPS-2794)
[APPS-2794]: https://uclalibrary.atlassian.net/browse/APPS-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove vue-router from external

- package.json
- pnpm-lock.yaml
- src/lib-components/DividerWayFinder.vue
- vite.config.ts
Connected to [APPS-2794](https://jira.library.ucla.edu/browse/APPS-2794)
[APPS-2794]: https://uclalibrary.atlassian.net/browse/APPS-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: APPS-2794

- .eslintrc
- package.json
- pnpm-lock.yaml
- src/lib-components/DateFilter.vue
- src/lib-components/SearchGeneric.vue
- src/lib-components/SectionRemoveSearchFilter.vue
- vite.config.ts
This PR will fix the static build issue caused by using umd file format
> feat: Revert vitebuild code added previously

- .github/workflows/ci.yml
- .github/workflows/percy.yml
https://uclalibrary.atlassian.net/browse/APPS-2808
> feat: Update workflows for merge to main

- .github/workflows/percy.yml
> fix: workflow dispatch indentation issue

- vite.config.ts
This may fix the active pinia error in Nuxt3 code base.
https://github.com/vuejs/pinia/discussions/1059#discussioncomment-3736999
> feat: externalize pinia in lib build

- vite.config.ts
Fix the `vite.config.js`
it was overwritten  by the last merge in component library repo
> fix: update vite.config.js external ['vue', 'vue-router', 'pinia']

- vite.config.ts
Connected to [APPS-2894](https://jira.library.ucla.edu/browse/APPS-2894)
[APPS-2894]: https://uclalibrary.atlassian.net/browse/APPS-2894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: APPS-2894   Fix storybook configure page mdx error

- src/lib-components/TabList.vue
- src/styles/default/_tab-list.scss
Connected to [APPS-2940](https://jira.library.ucla.edu/browse/APPS-2940), [APPS-2822](https://jira.library.ucla.edu/browse/APPS-2822), 
**Component Updated:** TabList.vue
**Preview:** https://deploy-preview-608--ucla-library-storybook.netlify.app/?path=/docs/tab-toggle--docs
**Notes:**
- Enhanced animation to tab slider
- Refactored code with Typescript
**Checklist:**
-   [x] I …
> feat: APPS 2940 Animate TabToggle component

- src/lib-components/FlexibleBlocks.vue
- src/stories/FlexibleBlocks.stories.js
- src/stories/TwoColLayoutWStickySideBar.stories.js
- src/stories/mock/SocialList.js
- src/styles/ftva/_section-wrapper.scss
Connected to [APPS-2963](https://jira.library.ucla.edu/browse/APPS-2963)
**Notes:**
1. This story is just started but needs to be updated for different flexible data for article/blog entry
2. Add useTheme composable
3. Add new component FlexibleHorizontalDivider to FlexibleBlocks component
4. Update `parsedBlocks` computed method to set theme to white and divider to false
5. Remove max-width for rich-text for ftva in the `ftva/_section-wrapper.scss`
[APPS-2963]: https://uclalibrary.atlassian.net/browse/APPS-2963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-2963   Update FlexibleBlocks component with FTVA theme

- src/stores/GlobalStore.js
Connected to [APPS-3000](https://jira.library.ucla.edu/browse/APPS-3000)
**File Updated:** src/stores/GlobalStore.js
**Notes:**
**Checklist:**
-   ~~[ ] I checked that it is working locally in the storybook~~
[APPS-3000]: https://uclalibrary.atlassian.net/browse/APPS-3000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
> chore: APPS-3000 Update global store with FTVA viewing info

- package.json
- pnpm-lock.yaml
- src/lib-components/BlockCallToAction.vue
- src/lib-components/ButtonDropdown.vue
- src/lib-components/TwoColLayoutWStickySideBar.vue
- src/stories/BlockCallToAction.stories.js
- src/stories/TwoColLayoutWStickySideBar.stories.js
- src/styles/default/_block-call-to-action.scss
- src/styles/ftva/_block-call-to-action.scss
Connected to [APPS-2999](https://jira.library.ucla.edu/browse/APPS-2999)
**Component Updated:** BlockCallToAction.vue
**Stories:** 
- ~/stories/BlockCallToAction.stories.js
- ~/stories/TwoColLayoutWStickySideBar.stories.js
**Notes:**
- Updated design tokens from `5.23.0` to ~~`5.26.0`~~ `5.27.0`
- Refactored component to use CAPI, Typescript and new theming setup
- Created FTVA `Slim` variant of CTA block
- Included additional icons, new `isCentered` prop to cue default or left (slim) alignment
- Variant's width should be set/constrained by a containing/parent element
- Updated component stories with new variant
<br>
**StoryBook Previews:**
- FTVA Slim, Left-Aligned, Titled, Using global data 
- https://deploy-preview-630--ucla-library-storybook.netlify.app/?path=/story/block-call-to-actio …
> feat: APPS-2999 Add BlockCTA FTVA variants

- .github/workflows/setup-workspace/action.yml
- package.json
- pnpm-lock.yaml
- src/lib-components/Flexible/BannerFeatured.vue
Connected to [APPS-3012](https://jira.library.ucla.edu/browse/APPS-3012)
A small PR to replace `Impact Report Story` category to `Impact Report Spotlight`
[APPS-3012]: https://uclalibrary.atlassian.net/browse/APPS-3012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update category for impact report story to impact report spotlight

- src/lib-components/BlockRemoveSearchFilter.vue
- src/lib-components/DateFilter.vue
- src/lib-components/SearchGenericFilters.vue
- src/lib-components/SectionRemoveSearchFilter.vue
- src/stories/DateFilter.spec.js
- src/stories/SectionRemoveSearchFilter.stories.js
Connected to [APPS-3100](https://jira.library.ucla.edu/browse/APPS-3100)
[APPS-3100]: https://uclalibrary.atlassian.net/browse/APPS-3100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3100 Decouple SectionRemoveSearchFilter

- src/lib-components/BaseCalendar.vue
- src/lib-components/BlockCardThreeColumn.vue
- src/styles/default/_base-calendar.scss
Connected to [APPS-3117](https://jira.library.ucla.edu/browse/APPS-3117)
**Components Updated:** BaseCalendar.vue, BlockCardThreeColumn.vue
**Notes:**
- Minor style/CSS updates to:
- Add border-radius to the bottom corners of calendar popup card
- Remove excess padding in tab labels/pills in 3-column-card component
**Checklist:**
-   [x] I have requested a PR review from the Dev team
[APPS-3117]: …
> fix: APPS-3117 Additional Component Fixes for EventListing Page

- src/lib-components/BlockCardWithImage.vue
- src/lib-components/CardMeta.vue
- src/stories/BlockCardWithImage.stories.js
- src/stories/CardMeta.stories.js
- src/stories/mock-api.json
- src/styles/ftva/_block-card-with-image.scss
- src/styles/ftva/_card-meta.scss
Connected to [APPS-3107](https://jira.library.ucla.edu/browse/APPS-3107)
- https://deploy-preview-677--ucla-library-storybook.netlify.app/?path=/story/card-meta--ftva-custom-title-and-desription
- https://deploy-preview-677--ucla-library-storybook.netlify.app/?path=/story/block-card-with-image--ftva-article-blog-listing
- https://deploy-preview-677--ucla-library-storybook.netlify.app/?path=/story/section-teaser-card--ftva-event-detail
[APPS-3107]: https://uclalibrary.atlassian.net/browse/APPS-3107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3107 create ftva variation of block card with image and card meta component for the article listing page

- README.md
- release.config.cjs
**Notes:**
Update release config to allow 'chore' and 'refactor' releases
> feat: update release config

- src/stories/TableComponent.stories.js
- src/styles/ftva/_table-component.scss
Connected to [APPS-3167](https://jira.library.ucla.edu/browse/APPS-3167)
**Component Updated:** TableComponent.vue
**Styles:** ~/styles/ftva/_table-component.scss
**Stories:** ~/stories/TableComponent.stories.js
**Preview:** http://localhost:6006/?path=/story/table-table-with-header--ftva-pale-blue-theme
**Notes:**
- Add new story showing paleblue theme
- CSS update to make theme's default full width 
**Checklist:**
-   [x] I have requested a PR review from the Dev team
-   [x] I used a …
> feat: APPS-3167 Update Table Component with PaleBlue theme

- packages/vue-component-library/release.config.cjs
Connected to [APPS-3134](https://jira.library.ucla.edu/browse/APPS-3134)
```
Error: semantic-release-monorepo: Incorrect plugin name type. Expected string but was {"preset":"angular","releaseRules":[{"type":"refactor","release":"patch"},{"type":"chore","release":"patch"}]}.
```
[APPS-3134]: https://uclalibrary.atlassian.net/browse/APPS-3134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: the plugin structure

- packages/vue-component-library/src/lib-components/FlexibleBlocks.vue
Connected to [APPS-3152](https://jira.library.ucla.edu/browse/APPS-3152)
**Notes:**
Very small PR to import new info.vue component into FlexibleBlocks.vue
**Checklist:**
-   ~~[ ] I assigned this PR to someone on the dev team to review~~
[APPS-3152]: https://uclalibrary.atlassian.net/browse/APPS-3152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3152 FlexibleBlocks add Info

- README.md
- package.json
- packages/vue-component-library/README.md
Connected to [APPS-3134](https://jira.library.ucla.edu/browse/APPS-3134)
ReadMe updates
[APPS-3134]: https://uclalibrary.atlassian.net/browse/APPS-3134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Update Readme at root and in the package

- .github/workflows/publish-to-npm.yml
Connected to [APPS-3134](https://jira.library.ucla.edu/browse/APPS-3134)
This fix for the failed published in the last PR
[APPS-3134]: https://uclalibrary.atlassian.net/browse/APPS-3134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update github actions

- packages/component-library-nuxt-module/package.json
- packages/vue-component-library/src/index.ts
- pnpm-lock.yaml
**Notes:**
Noticed flexible info blocks were not showing on ARSC page although data was correctly formed and sent, I think this is the issue
edit: also added some changes to package dependencies at Parinita's request
> feat: fix flexibleinfo export

- .gitignore
- packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue
- packages/vue-component-library/src/lib-components/SearchGeneric.vue
- packages/vue-component-library/src/stories/AlphabeticalBrowseBy.stories.js
Connected to [APPS-2314](https://jira.library.ucla.edu/browse/APPS-2314)
[APPS-2314]: https://uclalibrary.atlassian.net/browse/APPS-2314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add configuration prop for  All filter from alphabet browse by and add watcher to SearchGeneric component 

- packages/vue-component-library/package.json
- packages/vue-component-library/src/lib-components/SectionTeaserCard.vue
- packages/vue-component-library/src/stories/SectionTeaserCard.stories.js
- packages/vue-component-library/src/styles/default/_section-teaser-card.scss
- packages/vue-component-library/src/styles/ftva/_section-teaser-card.scss
- packages/vue-component-library/src/types/types.ts
- pnpm-lock.yaml
Connected to [APPS-3291](https://jira.library.ucla.edu/browse/APPS-3291)
**Component Updated:** SectionTeaserCard.vue
**Stories:** ~/stories/SectionTeaserCard.stories.js
**Notes:**
- Updated `SectionTeaserCard` component for Collections Listing Type page template
- Display `Watch Online` tag for watch-and-listen-online type
- Refactored component to make grid layout the default (which was the original/library website layout)   
- Added `gridLayout` prop to enable wrapping of cards (`true`), or horizontal scroll (`false`)
- Moved FTVA horizontal scroll styles to new `no-grid-layout` selector 
- A number of FTVA page templates will need to be updated with the new prop; see related ticket:
- [APPS-3303: Add new gridLayout prop to SectionTeaserCards on FTVA …
> feat: APPS-3291 Update SectionTeaserCard for Collection Listings Types

- packages/vue-component-library/src/lib-components/BlockPostSmall.vue
- packages/vue-component-library/src/lib-components/SectionPostSmall.vue
- packages/vue-component-library/src/stories/BlockPostSmall.stories.js
- packages/vue-component-library/src/stories/SectionPostSmall.stories.js
- packages/vue-component-library/src/styles/_base.scss
- packages/vue-component-library/src/styles/_ftva-theme.scss
- packages/vue-component-library/src/styles/default/_block-post-small.scss
- packages/vue-component-library/src/styles/default/_section-post-small.scss
- packages/vue-component-library/src/styles/ftva/_block-post-small.scss
- packages/vue-component-library/src/styles/ftva/_section-post-small.scss
Connected to [APPS-3292](https://jira.library.ucla.edu/browse/APPS-3292)
Updates the BlockPostSmall & SectionPostSmall components for the Collections Listing page.
[APPS-3292]: https://uclalibrary.atlassian.net/browse/APPS-3292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: APPS-3292 theme PostSmall component to match about our collections items

- packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue
- packages/vue-component-library/src/lib-components/VideoEmbed.vue
- packages/vue-component-library/src/stories/AlphabeticalBrowseBy.stories.js
- packages/vue-component-library/src/styles/default/_alphabetical-browse-by.scss
- packages/vue-component-library/src/styles/ftva/_alphabetical-browse-by.scss
thank you @tinuola for providing the solution , instead of watching on props we can just directly set the value from the prop to the data variable ref in onMounted lifecycle hook
> fix: Replace watcher with onMounted and fix videoembed undefined error on ftva when trailer is not an iframe code from craft

- packages/vue-component-library/src/lib-components/BaseCheckboxGroup.vue
- packages/vue-component-library/src/lib-components/BaseRadioGroup.vue
- packages/vue-component-library/src/lib-components/SearchGeneric.vue
- packages/vue-component-library/src/lib-components/SearchGenericFilters.vue
- packages/vue-component-library/src/lib-components/SearchInput.vue
- packages/vue-component-library/src/lib-components/SearchMenuItem.vue
- packages/vue-component-library/src/lib-components/SectionRemoveSearchFilter.vue
When route is search-site set searchwords to route.query.q
> fix: Search words reset

- packages/vue-component-library/src/lib-components/BlockMediaWithText.vue
- packages/vue-component-library/src/lib-components/Flexible/MediaWithText.vue
- packages/vue-component-library/src/stories/BlockMediaWithText.stories.js
- packages/vue-component-library/src/stories/Flexible_MediaWithText.stories.js
- packages/vue-component-library/src/stories/mock/BlockMediaWithText.js
- packages/vue-component-library/src/stories/mock/FTVAMedia.js
- packages/vue-component-library/src/stories/mock/Flexible_MediaWithText.js
- packages/vue-component-library/src/styles/default/_block-media-with-text.scss
- packages/vue-component-library/src/styles/default/_flexible-media-with-text.scss
- packages/vue-component-library/src/styles/ftva/_block-media-with-text.scss
- packages/vue-component-library/src/styles/ftva/_flexible-media-with-text.scss
Connected to [APPS-3320](https://jira.library.ucla.edu/browse/APPS-3320)
**Components Updated:** 
- BlockMediaWithText.vue
- Flexible/MediaWithText.vue
**Stories Updated:** 
- BlockMediaWithText.stories.js
- Flexible_MediaWithText.stories.js
**Notes:**
- Added theme composable to `BlockMediaWithText`, `FlexibleMediaWithText`
- Moved styles into stylesheets for both component; created FTVA style variants
- Updated mock data with FTVA data for `BlockMediaWithText`, `FlexibleMediaWithText` and `FlexibleBlock`
- Updated stories for `BlockMediaWithText`, `FlexibleMediaWithText`
- Confirmed that there are no regressions in current stories
**Previews:**
- BlockMediaWithText:
-  Previous State - No FTVA: https://deploy-preview-736--ucla-library-storybook.netlify.app/?path=/docs/block-media-with-te …
> feat: APPS-3320 Create MediaWithText FTVA variants

- packages/vue-component-library/src/lib-components/SectionPostSmall.vue
- packages/vue-component-library/src/stories/SectionPostSmall.stories.js
- packages/vue-component-library/src/stories/mock/BlockMediaWithText.js
- packages/vue-component-library/src/stories/mock/FTVAMedia.js
- packages/vue-component-library/src/stories/mock/Flexible_MediaWithText.js
- packages/vue-component-library/src/styles/default/_section-post-small.scss
- packages/vue-component-library/src/styles/ftva/_block-card-with-image.scss
- packages/vue-component-library/src/styles/ftva/_block-media-with-text.scss
- packages/vue-component-library/src/styles/ftva/_block-post-small.scss
- packages/vue-component-library/src/styles/ftva/_section-post-small.scss
Connected to [APPS-3356](https://jira.library.ucla.edu/browse/APPS-3356)
**Components Updated:** 
- Code:
- SectionPostSmall
- Styles / Mocks / Stories:
- BlockMediaWithText
- FlexibleCardWithImage
- BlockPostSmall
- SectionPostSmall
**Notes:**
- Fixed line-height of link in BlockMediaWithText's FTVA variant
- Updated MediaWithText mocks with longer link text to confirm line-height fix
- Removed box-shadow hover on FlexibleCardwithImage noBackground style option (per UX)
- Updated FlexibleBlock mock file with additional data to display whiteBackground option
- Refactored PostSmall component
- Fixed issue of missing section summary causing component layout to break
- Added new prop `fullWidth` to Section component to set if items should span width of parent container or be a set/standard …
> fix: APPS-3356 Component Fixes for Storytelling Page

- packages/vue-component-library/src/lib-components/BlockStaffArticleList.vue
- packages/vue-component-library/src/stories/SectionStaffArticleList.stories.js
- packages/vue-component-library/src/stories/mock/FTVASearchResultsData.js
Connected to [APPS-3375](https://jira.library.ucla.edu/browse/APPS-3375)
**Notes:**
date is used to pass postDate on FTVA searchresults page 
[APPS-3375]: https://uclalibrary.atlassian.net/browse/APPS-3375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: use and logic instead of or logic operator

- packages/vue-component-library/src/lib-components/ImageSlider.vue
- packages/vue-component-library/src/stories/ImageSlider.stories.js
Connected to [APPS-3376](https://jira.library.ucla.edu/browse/APPS-3376)
**Notes:**
Images were reversed! Also made sure to pass the image objects alt text to the img element
**Checklist:**
[APPS-3376]: https://uclalibrary.atlassian.net/browse/APPS-3376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add alt text

- .github/workflows/label-by-title.yml
Connected to [APPS-3404](https://jira.library.ucla.edu/browse/APPS-3404)
**Notes:**
Add labels by title GH action
[APPS-3404]: https://uclalibrary.atlassian.net/browse/APPS-3404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: Add github action for adding labels when PR is opened with a conventional commit title

- .github/workflows/ci.yml
After merging a PR I forgot to use run_id instead of pull request for cypress job
> fix: cypress after merge

- .github/workflows/ci.yml
> fix: Add check

- packages/vue-component-library/src/lib-components/NavPrimary.vue
- packages/vue-component-library/src/stories/BlockCardThreeColumn.stories.js
- packages/vue-component-library/src/styles/ftva/_header-sticky.scss
- packages/vue-component-library/src/styles/ftva/_nav-primary.scss
Connected to [APPS-3033](https://jira.library.ucla.edu/browse/APPS-3033)
**Component Updated:** 
- NavPrimary.vue
- Styles for HeaderSticky.vue and NavPrimary.vue
**Notes:**
- Page overflow was primarily coming from pseudo-element styling meant to extend background of nav and search menus
- Due to UX requirement to have menus overlay rather than push down page content, menus were absolutely positioned; however, this made it difficult to position the search menu after the nav menu AND also have its dropdown (`more-menu`) span the entire page width, which was possibly why the pseudo-elements were added
- After extended/multiple unsuccessful attempts to solve this via CSS alone, the least cumbersome solution was to conditionally add the search icon to the nav menu list at large screen …
> fix: APPS-3033 Remove Nav Menu Page Overflow
