UCLALibrary/ucla-library-website-components

.github/workflows/ci.yml
.github/workflows/percy.yml

- Sets up Percy job to run on manual trigger
- adds cache action to 'storybook' job in ci.yml - this well save a cache so the percy job doesn't need to regenerate it

chore: set up Percy CI job

---

src/lib-components/BannerFeatured.vue

fix: Fix for squashed button text in BannerFeatured

---

build/rollup.config.js
src/lib-components/BannerFeatured.vue
src/lib-components/BannerHeader.vue
src/lib-components/BannerText.vue
src/lib-components/BlockAmenities.vue
src/lib-components/BlockCallToAction.vue
src/lib-components/BlockCardWithIllustration.vue
src/lib-components/BlockHighlight.vue
src/lib-components/BlockLocationListItem.vue
src/lib-components/BlockMediaWithText.vue
src/lib-components/IconWithLink.vue
src/lib-components/SectionStaffArticleList.vue
src/stories/SectionStaffArticleList.stories.js

Connected to [APPS-1758](https://jira.library.ucla.edu/browse/APPS-1758)
Lazy load components where needed in:
[BannerFeatured.vue ](https://github.com/UCLALibrary/library-website-nuxt/blob/main/components/BannerFeatured.vue#L141)
[BannerHeader.vue ](https://github.com/UCLALibrary/library-website-nuxt/blob/main/components/BannerHeader.vue#L193)
[BannerText.vue ](https://github.com/UCLALibrary/library-website-nuxt/blob/main/components/BannerText.vue#L157)
[BlockAmenities.vue ](https://github.com/UCLALibrary/library-website-nuxt/blob/main/components/BlockAmenities.vue#L30)
[ BlockCallToAction.vue  ](https://github.com/UCLALibrary/library-website-nuxt/blob/main/components/BlockCallToAction.vue#L26)
[BlockCardWithIllustration.vue](https://github.com/UCLALibrary/library-website-nuxt/blob/main/c …

fix: APPS-1758 lazy load components

---

src/lib-components/BannerText.vue
src/lib-components/BlockCallToAction.vue
src/lib-components/BlockEvent.vue
src/lib-components/BlockSpaces.vue
src/lib-components/ButtonLink.vue
src/lib-components/ButtonMore.vue

- ux updates to the button-link and button-more components
- block-event should be refactored to use the button-link component instead of the router-link ([APPS-1776](https://jira.library.ucla.edu/browse/APPS-1776))

feat: qa button-link and button-more component

---

src/lib-components/Flexible/MediaGallery.vue
src/mixins/getSectionName.js

Connected to [APPS-1719](https://jira.library.ucla.edu/browse/APPS-1719)
**Component Updated:** src/lib-components/Flexible/MediaGallery.vue
**Notes:**
Add null check for getsection name for external resource on help topics page.
If someone accidentally adds video to media gallery it will not give 404
**Checklist:**

fix: add null checks

---

.github/workflows/lint-pr.yml

Adds `agilepathway/label-checker` to `.github/workflows/lint-pr.yml` to require PR labels in addition to a semantic PR title

ci: Lint PR labels and titles

---

dev/serve.vue
src/lib-components/BlockSponsor.vue
src/lib-components/FooterMain.vue
src/lib-components/FooterPrimary.vue
src/lib-components/FooterSock.vue
src/lib-components/index.js
src/stories/FooterMain.spec.js
src/stories/FooterMain.stories.js

Connected to [APPS-1778](https://jira.library.ucla.edu/browse/APPS-1778)
Currently FooterPrimary, FooterSock, and FooterSponsor are using the footer tag as the parent element. Instead, we need a single footer tag that includes each of these footer sections.
Acceptance criteria:
There is a single footer tag used as a container that can include the FooterPrimary, FooterSock and/or FooterSponsor

feat: add footerMain

---

src/lib-components/Flexible/MediaGallery/BannerImage.vue
src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
src/lib-components/ResponsiveImage.vue
src/stories/MediaGallery_ThumbnailCard.stories.js
src/stories/mock-api.json

Connected to [APPS-1804](https://jira.library.ucla.edu/browse/APPS-1804)
Add focalPoint from craft image data as object-position css property.
https://deploy-preview-122--ucla-library-storybook.netlify.app/?path=/story/media-gallery-thumbnail-card--focal-point

fix: Add focal point to responsive image

---

.github/workflows/ci.yml

Connected to [APPS-1820](https://jira.library.ucla.edu/browse/APPS-1820)
**Notes:**
GH Action ci.yml updated to deploy storybook to Netlify on merge to main.

ci: Add storybook deploy on push to main

---

src/lib-components/SectionWrapper.vue

- all margins: set only for child components, instead of all children
- vertical margins: only set top of first child, bottom of last, so we don't override spacing between elements within the section-wrapper

fix: SectionWrapper child component margins

---

src/lib-components/Flexible/SimpleCards.vue
src/stories/mock/Flexible_SimpleCards.js

fix: update flexible simple cards path to `uri` from `slug` to match MEAP query

fix: update flexible simple cards path

---

src/lib-components/FlexibleBlocks.vue
src/lib-components/FooterSponsor.vue

Connected to [UX-692](https://jira.library.ucla.edu/browse/UX-692)
Adds text (to come from development, will be the same for all microsites) to FooterSponsor
**Checklist:**
-   [/] I checked that it is working locally in the dev server
-   [/] I checked that it is working locally in the storybook
-   [/] I added a screenshot of it working
-   [/] UX has reviewed and approved this
-   [/] I used a conventional commit message
-   [/] I assigned myself to this PR
-

feat: adds development text to footer-sponsor

---

src/lib-components/BlockHighlight.vue
src/lib-components/BlockSpaces.vue
src/lib-components/IconWithLink.vue
src/lib-components/SectionWrapper.vue

Connected to [APPS-1839](https://jira.library.ucla.edu/browse/APPS-1839)
**Notes:**
Replaced p tag with div and replace v-html to v-text in some cases.
Files changed:
- src/lib-components/BlockHighlight.vue
- src/lib-components/BlockSpaces.vue
- src/lib-components/IconWithLink.vue
- src/lib-components/SectionWrapper.vue
It's ideal to not use v-html anywhere. https://eslint.vuejs.org/rules/no-v-html.html
**Checklist:**
-   [x] I used a …

fix: replace p tag with div and replace v-html to v-text in some cases

---

src/lib-components/BlockHighlight.vue
src/stories/BlockHighlight.stories.js

fix: v-text to v-html
Added html to story as an example
bug seen on meap site where rich text was not being transformed to html

fix: v-text to v-html

---

src/lib-components/HeaderMainResponsive.vue
src/lib-components/NavMenuItem.vue
src/lib-components/NavMenuItemResponsive.vue
src/lib-components/NavPrimary.vue
src/lib-components/NavSecondary.vue
src/stories/HeaderMainResponsive.stories.js
src/stories/NavPrimary.stories.js

Connected to [APPS-1843](https://jira.library.ucla.edu/browse/APPS-1843)
modified:   src/lib-components/HeaderMainResponsive.vue
modified:   src/lib-components/NavMenuItem.vue
modified:   src/lib-components/NavMenuItemResponsive.vue
modified:   src/lib-components/NavPrimary.vue
modified:   src/lib-components/NavSecondary.vue
modified:   src/stories/HeaderMainResponsive.stories.js
modified:   src/stories/NavPrimary.stories.js
**Notes:**
This will fix the keyboard tab use in the navigation on the desktop. Also will add acronym support on smaller viewports.
**Checklist:**
-   [x] I …

fix: keyboard tab key use and acronym

---

src/mixins/getParentPageUrl.js

Update logic of parent page url 
When `output` array length is equal to 2 (like ["", "page"] then the parent page is the homepage)

fix: update mixin

---

src/lib-components/FlexibleBlocks.vue
src/stories/FlexibleBlocks.stories.js

Connected to [APPS-1872](https://jira.library.ucla.edu/browse/APPS-1872)
fix: flexible blocks' last item is always white

fix: flexible blocks' last item is always white

---

src/lib-components/BlockStaffArticleList.vue
src/stories/BlockStaffArticleList.stories.js

Connected to [APPS-1889](https://jira.library.ucla.edu/browse/APPS-1889)
fix: add default image to BlockStaffArticleList

fix: add default image to BlockStaffArticleList

---

src/lib-components/HeaderSmart.vue

fixes a bug where menu links were not included in the static render, and thus not crawled, leaving some pages undiscovered

fix: use the desktop Header in static build

---

src/mixins/getMeapParentPageTitle.js
src/mixins/getParentPageUrl.js

Connected to [APPS-1892](https://jira.library.ucla.edu/browse/APPS-1892)
In static mode routes have a trailing slash appended to them. 
NavBreadcrumb should work for `/projects/justino-valentim-collection/` or `/projects/justino-valentim-collection`

fix: update navbreadcrumb

---

src/lib-components/HeaderMainResponsive.vue
src/lib-components/HeaderSmart.vue

the previous fix, in HeaderSmart for the main site, was hydrating incorrectly, resulting in both nav headers appearing
this PR reverts changes to HeaderSmart and instead modifies HeaderMainResponsive to always render the menu content (but only show it when opened)
https://github.com/UCLALibrary/meap-website-nuxt/pull/88, which would have made the same bad fix to the MEAP site, has been cancelled unmerged. The improved HeaderMainResponsive is used in both sites.

fix: disappearing menus, part 2

---

src/lib-components/SectionWrapper.vue

Connected to [APPS-1904](https://jira.library.ucla.edu/browse/APPS-1904)
- Updates SectionWrapper with .section-banner styling to override margin-top on BannerHeader components
- Resolves spacing issue on MEAP News and Resource detail pages here at the component level
**Checklist:**
meap-website-nuxt dev server

feat: updates section-banner spacing

---

src/lib-components/BannerHeader.vue
src/stories/BannerHeader.stories.js

Connected to [APPS-1912](https://jira.library.ucla.edu/browse/APPS-1912)
Stack the byline section for consistency across all BannerHeaders

fix: APPS-1912 Update Byline in BannerHeader

---

src/lib-components/GridGallery.vue

Connected to [UX-713](https://jira.library.ucla.edu/browse/UX-713)
- updates featured card to display full width with text below
- removes svg
- replaces spacing with design tokens
**Checklist:**
-

fix: removes svg and updates featured layout

---

src/lib-components/NavPrimary.vue

addresses a bug where, after selecting an item from the nav menu, that item received browser focus and so was rendered visible
before: https://6323a033c2a821125c629a06--ucla-library-storybook.netlify.app/?path=/story/nav-primary--default
after: https://deploy-preview-192--ucla-library-storybook.netlify.app/?path=/story/nav-primary--default

fix: clear focus when closing Nav menu

---

src/lib-components/Media/Item.vue
src/stories/MediaItem.spec.js
src/stories/MediaItem.stories.js

Connected to [APPS-1975](https://jira.library.ucla.edu/browse/APPS-1975)
**Component Created:** ~/lib-components/Media/Item.vue
**Stories:** ~/stories/MediaItem.stories.js
**Spec:** ~/stories/MediaItem.spec.js
**Notes:**
Takes a 'media-item' object representing a piece of media (only image and video to start, audio and embeds to come), and passes it on to the correct subcomponent for its media type (e.g. ResponsiveImage or ResponsiveVideo). This can be specified explicitly with a prop or figured out by inspecting the media-item prop
Props are based on ResponsiveImage and ResponsiveVideo with some changes, but props like "src" or "videoUrl" are removed. These should always be passed as attributes of the "media-item" object. The idea is that "media-item" has all the information that is …

feat: MediaItem component

---

src/lib-components/BannerText.vue
src/lib-components/NavPrimary.vue

Connected to [APPS-1733](https://jira.library.ucla.edu/browse/APPS-1733)
- removes support-us links display in NavPrimary
- updates contact-info spacing in BannerText to be consistent with BannerHeader
**Checklist:**

feat: updates NavPrimary and BannerText spacing

---

src/lib-components/BannerFeatured.vue
src/lib-components/Flexible/BannerFeatured.vue
src/stories/BannerFeatured.stories.js
src/stories/BannerHeader.stories.js
src/stories/MediaItem.stories.js
src/stories/ResponsiveVideo.stories.js
src/stories/mock-api.json

Connected to [APPS-1996](https://jira.library.ucla.edu/browse/APPS-1996)
fix: APPS-1996 banner featured image video logic
- Update Banner Featured to decide whether a file is a video or an image. 
- Remove video prop from BannerFeatured because data only comes from Image.gql fragment

fix: APPS-1996 banner featured image video logic

---

src/lib-components/BlockHighlight.vue
src/stories/BlockHighlight.stories.js

fix: add molecule svg with blue background when there is no event image prop for blockhighlight

---

src/lib-components/NavPrimary.vue
src/stories/NavPrimary.stories.js

Connected to [APPS-2034](https://jira.library.ucla.edu/browse/APPS-2034)
Impact Report home page cannot be a nuxt link on drupal environment

fix: Impact Report home page cannot be a nuxt link on drupal environment

---

src/lib-components/Media/Item.vue

[The javascript safe access operator `?.`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is newer syntax with limited support, possible requiring babel transpilation. Storybook could handle it, but it causes an error in our nuxt setup

fix: don't use `?.` operator in MediaItem

---

src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
src/lib-components/ResponsiveImage.vue

Connected to [UX-834](https://jira.library.ucla.edu/browse/UX-834)
- adds object-fit: cover property to responsive image to resolve staff profile image bug
- adds clamp to media gallery caption text
**Checklist:**

fix: updates responsive image and gallery caption

---

src/lib-components/FlexibleBlocks.vue
src/lib-components/ModalLightbox.vue
src/stories/ModalLightbox.spec.js
src/stories/ModalLightbox.stories.js

Connected to [APPS-1590](https://jira.library.ucla.edu/browse/APPS-1590)
**Component Created:** ModalLightbox.vue
**Stories:** ~/stories/ModalLightbox.stories.js
**Spec:** ~/stories/ModalLightbox.spec.js
**Notes:**
Tried to adapt something that could be used for both MediaGallery and Campus Map layouts, but that proved too difficult. This is the Map layout, and can be generalized to other cases. Main content is inserted in a slot, and presented in the middle 75% of each window axis.
Also fixes an error warning about loading SectionHeader in FlexibleBlocks
**Checklist:**
-   [ ] I …

feat: ModalLightbox component

---

src/lib-components/MastheadPrimary.vue
src/stories/MastheadPrimary.stories.js

Connected to [APPS-2092](https://jira.library.ucla.edu/browse/APPS-2092)
Refactor MastHead Primary to take search links as props, not hardcoded in data

refactor: refactor masthead primary search links

---

src/lib-components/MastheadPrimary.vue
src/lib-components/SearchHome.vue
src/stories/MastheadPrimary.stories.js

- Remove `target` from Masthead Primary story
- Update `SearchHome` to use `SmartLink`

fix: update masthead primary story and add smart-link to search home

---

src/lib-components/MastheadSecondary.vue

https://github.com/UCLALibrary/ucla-library-website-components/pull/274 requires this addition for styling
- updates rich-text in masthead-secondary to white

fix: update masthead text color to white

---

src/mixins/removeHtmlTruncate.js

Uses lodash's _unescape function. Also replaces truncate logic with the lodash _truncate, which will give better results for a few edge cases.

fix: removeHtmlTruncate unescape HTML entities

---

src/lib-components/BlockAmenities.vue
src/lib-components/BlockEvent.vue
src/lib-components/BlockGenericList.vue
src/lib-components/BlockLocationListItem.vue
src/lib-components/BlockSimpleCard.vue
src/lib-components/BlockStaffDetail.vue
src/lib-components/BlockStaffList.vue
src/lib-components/BlockStaffSubjectLibrarian.vue
src/lib-components/GridGallery.vue
src/lib-components/SearchGeneric.vue
src/lib-components/SectionStaffSubjectLibrarian.vue
src/lib-components/SectionWrapper.vue
src/lib-components/StoryWithImage.vue

Reverting this PR https://github.com/UCLALibrary/ucla-library-website-components/pull/282, as this is causing scoped slots error on search pages, also removing v-html where it is not needed

fix: Fix hydration part2

---

src/lib-components/BlockLocationListItem.vue
src/lib-components/SectionLocationList.vue
src/stories/BlockLocationListItem.stories.js
src/stories/SectionLocationList.stories.js

Connected to [APPS-2143](https://jira.library.ucla.edu/browse/APPS-2143)
https://deploy-preview-314--ucla-library-storybook.netlify.app/?path=/story/section-location-list--default
Cards display accurate hours.
Only UCLA libraries display hours.

fix: update location list hours

---

src/lib-components/Media/Item.vue
src/stories/mock/Media.js

closes https://jira.library.ucla.edu/browse/APPS-2099
- when craft inserts a <figure> tag around embedded iframe, ensures that it fills the available MediaItem space
- override hard-coded iframe width and height

fix: video embed display

---

src/lib-components/BlockSpaces.vue
src/lib-components/SiteNotificationAlert.vue
src/stories/BlockSpaces.stories.js
src/stories/SiteNotificationAlert.stories.js
src/stories/mock-api.json

Connected to [APPS-2172](https://jira.library.ucla.edu/browse/APPS-2172)
Connected to [APPS-2169](https://jira.library.ucla.edu/browse/APPS-2169)
Connected to [APPS-2158](https://jira.library.ucla.edu/browse/APPS-2158)
- replaces plain text with rich text for BlockSpaces and SiteNotificationAlert
- increases SiteNotificationAlert display time
- adjusts SiteNotificationAlert styling
* to-do: update stories with rich-text

feat: use rich-text in site alert and spaces, increase alert display time

---

src/lib-components/BlockHighlight.vue
src/stories/SectionTeaserCard.stories.js
src/stories/SectionTeaserHighlight.stories.js
src/stories/SectionTeaserList.stories.js

Connected to [APPS-2168](https://jira.library.ucla.edu/browse/APPS-2168)
- updates block-highlight to display placeholder image at appropriate heights for most common devices (dynamic height to come in responsive-image update, post launch)
https://deploy-preview-326--ucla-library-storybook.netlify.app/?path=/story/section-teaser-card--default

fix: update placeholder image height

---

src/lib-components/DividerWayFinder.vue

adds search-margin styling at component level so that we can remove styling from page templates

feat: add search-margin styling to divider

---

src/lib-components/BlockSimpleCard.vue
src/stories/BlockSimpleCard.stories.js

It looks like chrome was applying `-webkit-line-clamp` by shrinking the text box and inserting an ellepsis, but then letting the box grow again and reveal more lines of text when applying `flex-grow`.
This PR disables `flex-grow` and inserts an empty spacer div to keep the icon at the bottom of the card.

fix: SimpleCard truncaton

---

src/lib-components/RichText.vue

Connected to [APPS-2208](https://jira.library.ucla.edu/browse/APPS-2208)
firefox:
chrome:
safari:

fix: external link styling

---

src/lib-components/BlockHighlight.vue

fix: height of block highlight used in section teaser list

---

src/lib-components/BlockHours.vue

fix: fix blockhours url
from local linking:

fix: fix blockhours url

---

src/lib-components/BlockHighlight.vue
src/stories/BlockHighlight.stories.js

Connected to [WST-116](https://jira.library.ucla.edu/browse/WST-116)
sets max-width for highlight title on tablet and mobile to prevent text overlaying on image
https://deploy-preview-340--ucla-library-storybook.netlify.app/?path=/story/block-highlight--long-title-no-date-no-eyebrow

fix: BlockHighlight responsive title max-width

---

src/lib-components/SectionWrapper.vue

Connected to [APPS-2338](https://jira.library.ucla.edu/browse/APPS-2338) && [APPS-2319](https://jira.library.ucla.edu/browse/APPS-2319)
Change section-summary to `richtext` in section wrapper so the styles in the Craft are displayed in production.

fix: change section summary to richtext in section wrapper

---

src/lib-components/RichText.vue

Connected to [APPS-2055](https://jira.library.ucla.edu/browse/APPS-2055)
Adds styles to work with adding a halfWidth option for images to the redactor plugin
[APPS-2055]: https://uclalibrary.atlassian.net/browse/APPS-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update styles to work with halfWidth option in redactor

---

package-lock.json
package.json

fixes issues with repeated duplicate svg ids

chore: update to latest design tokens

---

src/lib-components/SearchGeneric.vue
src/lib-components/SearchInput.vue

connected to [APPS-2541](https://uclalibrary.atlassian.net/browse/APPS-2541)
emits a "search-ready" event which triggers a route update, api call, &c in library-website-nuxt
The only way to test this is locally with `npm run build && npm link` and `npm link ucla-library-website-components` in the website repo. I can confirm that it fixed the issue.
[APPS-2541]: https://uclalibrary.atlassian.net/browse/APPS-2541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update search when clearing search bar

---

src/lib-components/Flexible/PullQuote.vue
src/lib-components/PullQuote.vue
src/lib-components/index.js
src/stories/Flexible_PullQuote.spec.js
src/stories/Flexible_PullQuote.stories.js
src/stories/PullQuote.stories.js
src/types/flexible_types.ts

Connected to [APPS-2562](https://uclalibrary.atlassian.net/jira/software/c/projects/APPS/boards/12?selectedIssue=APPS-2562)
**Component Created:** `Flexible/PullQuote.vue`
**Stories:** `~/stories/Flexible_PullQuote.stories.js`
**Spec:** `~/stories/Flexible_PullQuote.spec.js`
**Notes:**
May have to add  this v-deep page level because of the RichText styling..
```
:deep(.pull-quote) {
padding: 24px var(--spacing-text-left);
--spacing-text-left: 64px;
--container-width: $container-m-text + px;
}
```
---
---
---
Updates `PullQuote.vue` with `<RichText>` for the text
**Checklist:**
- …

feat: APPS:2562 add Flexible/PullQuote component to vue3

---

src/lib-components/SearchGenericFilters.vue

Connected to [APPS-2265](https://jira.library.ucla.edu/browse/APPS-2265)
**Notes:**
Edited search generic filters to allow closing the filter dropdowns when clicking outside. The SearchGeneric storybook should now show the same behavior as the vue 2 version, where clicking outside the dropdowns automatically closes them https://ucla-library-storybook.netlify.app/?path=/story/search-generic--default
**Checklist:**
-   [X ] I checked that it is working locally in the dev server
-   [X ] I checked that it is working locally in the storybook
-   [X ] I checked that it is working locally in the 
-   [X ] I used a …

feat: APPS-2265, Add clickoutside feature to search-generic component

---

src/lib-components/SearchHome.vue
src/stories/SearchHome.spec.js

Connected to [APPS-2668](https://jira.library.ucla.edu/browse/APPS-2668)
**Component Edited:** SearchHome.vue
**Spec Edited:** ~/stories/SearchHome.spec.js, added a story for this requirement
**Notes:**
Sneaky error where we were passing the entire ref object for queryParam, instead of just the queryParam.value as a simple string
**Checklist:**
-   [ X] I checked that it is working locally in the dev server
-   [ X] I checked that it is working locally in the storybook
-   [ X] I assigned this PR to someone on the dev team to review
-   [ X] I used a conventional commit message
-   [ X] I assigned myself to this PR …

fix: APPS-2668 SearchHome.vue query param should be q

---

src/lib-components/BlockStaffDetail.vue
src/stories/BlockStaffDetail.stories.js

Connected to [APPS-2675](https://jira.library.ucla.edu/browse/APPS-2675)
**Component Edited:** BlockStaffDetail.vue
**Stories Edited:** ~/stories/BlockStaffDetail.stories.js
**Notes:**
images won't display because our mock storybook data is bugged, it has the entire image object being passed as the src argument for the responsiveImage child component, this means the responsiveImage component in BlockStaffDetail.vue never renders with actual data, and throws errors about getting a string when it expects an object
**Checklist:**
-   [X ] I checked that it is working locally in the dev server
-   [X ] I checked that it is working locally in the storybook
-   [ ] UX …

fix: APPS-2675 fix BlockStaffDetail.vue image type

---

src/lib-components/SearchInput.vue

Connected to [APPS-2665](https://jira.library.ucla.edu/browse/APPS-2665)
**Notes:**
Needed to add additional syntax to get the child component to emit the 'clear' event to its parent 
**Checklist:**
-   [X ] I checked that it is working locally in the dev server
-   [ X] I checked that it is working locally in the storybook
-   [X ] I used a conventional commit message
-   [X ] I assigned myself to this PR
[APPS-2665]: https://uclalibrary.atlassian.net/browse/APPS-2665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

fix: APPS-2665 When user clicks the x on search keyword, the search is not triggered automatically

---

src/stories/CardMeta.stories.js

Connected to [APPS-2557](https://jira.library.ucla.edu/browse/APPS-2557)
**Stories Edited:** ~/stories/CardMeta.stories.js
**Notes:**
I verified that these 2 changes were present in the branch:
Change 1: Highlight Text prop should be displayed using RichText component that can handle `<a>` tags, test data should test for `<a> `tags
[fix: APPS-2493 Hyperlink styling needed in FPB Highlight summary field by jendiamond · Pull Request #443 · UCLALibrary/ucla-library-website-components](https://github.com/UCLALibrary/ucla-library-website-components/pull/443) 
Solution:
As BlockHighlight.vue no longer exists, we needed to check that the components it was split into (BlockCardWithImage, BlockFloatingHighlight, BlockClippedDate) all had this behavior.
Luckily, all 3 components use CardMeta to …

chore: APPS-2557 carryover improvements from nuxt2 branch

---

src/lib-components/SearchInput.vue

Connected/Related to [APPS-2711](https://jira.library.ucla.edu/browse/APPS-2711)
**Component Updated:** SearchInput.vue
**Notes:**
On Nuxt3 pages that have the search input component, the skip-to-main-content functionality was not working properly. On page load, tab focus would jump into the search input and get trapped there. Troubleshooting revealed that a [line of code in the Vue2 version of the SearchInput component](https://github.com/UCLALibrary/ucla-library-website-components/blob/7f1f15ba1ac3cb0efe1ccd8fb9768d45bd8b1290/src/lib-components/SearchInput.vue#L126) was missing in the migrated version. This PR updates the Vue3 component with the omitted code.
**Checklist:**
-   [ ] I checked that it is working locally in the …

fix: Fix tab focus in-out of search input field

---

package.json
vite.config.ts

fix following error on nuxt3 branch
```
ERROR  [nuxt] [request error] [unhandled] [500] exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/parinitamulak/library-website-nuxt/node_modules/.pnpm/ucla-library-website-components@2.39.0-alpha.96_typescript@5.5.3_vue-router@4.4.0_vue@3.4.31/node_modules/ucla-library-website-components/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
This file is being treated as an ES module because it has a '.js' file extension and './node_modules/.pnpm/ucla-library-website-components@2.39.0-alpha.96_typescript@5.5.3_vue-router@4.4.0_vue@3.4.31/node_modules/ucla-library-website-components/package.json' …
```

feat: fix csbuild

---

src/lib-components/NavBreadcrumb.vue

**Notes:**
I took a shot at reducing the template code needed for breadcrumb. I did this by adding a bit of logic to format the classic data into the same data structure as the newer data. 
For tinu to decide if she likes this better or prefers current implementation. Just close this if you dont want to merge it in.

chore: refactor navbreadcrumb template for Tinu review

---

src/lib-components/ResponsiveVideo.vue
src/lib-components/VideoEmbed.vue
src/stories/ResponsiveVideo.stories.js
src/stories/VideoEmbed.spec.js
src/stories/VideoEmbed.stories.js

Connected to [APPS-2789](https://jira.library.ucla.edu/browse/APPS-2789) | [ISSUE-536](https://github.com/UCLALibrary/ucla-library-website-components/issues/536)
https://deploy-preview-563--ucla-library-storybook.netlify.app/?path=/story/global-videoembed--with-custom-imageand-icon
**Component Updated:** `ResponsiveVideo.vue`
**Stories:** `~/stories/ResponsiveVideo.stories.js`
**Notes:**
This component create a responsive iframe and places a custom poster image over it if one is supplied. It also replaces the default youtube play arrow. 
Based on this component request: https://github.com/UCLALibrary/ucla-library-website-components/issues/536
**Checklist:**
-   [ ] …

feat: Create Component FTVA VideoEmbed

---

src/lib-components/SmartLink.vue

Connected to [APPS-2811](https://jira.library.ucla.edu/browse/APPS-2811)
In Nuxt2 Percy snap shot baselines have a trailing slash, but in Nuxt3 Percy is creating snapshots with no trailing slash, so new snaps are created for the same URLs. To avoid this, Nuxt3 prefers to use NuxtLink with a trailing slash appended, but since we are using a component library we cannot use NuxtLink in this repo, hence the solution is to modify SmartLink component to append a trailing slash for the routes to be similar to nuxt2 for Percy final check, we can rethink about trailing slash for all the sites once website and Meap is migrated.
[APPS-2811]: https://uclalibrary.atlassian.net/browse/APPS-2811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add trailing slash for internal links for percy to not create new snapshots

---

src/lib-components/NavBreadcrumb.vue
src/lib-components/SectionTeaserCard.vue
src/stories/NavBreadcrumb.stories.js

Connected to [APPS-2847](https://jira.library.ucla.edu/browse/APPS-2847)
**Component Updated:** NavBreadcrumb}.vue
**Notes:**
URIs tested:
- `/events/la-r%C3%A9gion-centrale-03-08-24`
- `/events/la-région-centrale-03-08-24`
Browsers tested: 
- Chrome, Firefox, Edge, Safari
**Checklist:**
-   ~~[ ] I checked that it is working locally in the storybook~~
-   [x] I have requested a PR  review from the dev team
[APPS-2847]: …

fix: APPS-2847 NavBreadcrumb URI encoding

---

package.json
pnpm-lock.yaml
src/lib-components/SectionTeaserCard.vue
src/styles/ftva/_block-info.scss

Connected to [APPS-2843](https://uclalibrary.atlassian.net/browse/APPS-2843)
1. TICKET INFO: @include heading-grey;
2. the stroke under: @include grey-blue;
3. bullet points: @include body-grey;
4. bullet text: @include ftva-body-2;
5. add 10px margin below button
No changes were made to `src/lib-components/SectionTeaserCard.vue` it is just linting
[APPS-2843]: https://uclalibrary.atlassian.net/browse/APPS-2843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: APPS-2843 Component BlockInfo Styling updates

---

src/lib-components/VideoEmbed.vue

Connected to [APPS-2856](https://jira.library.ucla.edu/browse/APPS-2856)
**Component Created:** VideoEmbed.vue
**Preview:**
- https://deploy-preview-578--ucla-library-storybook.netlify.app/?path=/story/global-videoembed--with-custom-imageand-icon
- https://deploy-preview-578--ucla-library-storybook.netlify.app/?path=/story/section-screening-details--multiple-screenings
**Screenshots:**
**Checklist:**
-   [x] I used a conventional …

fix: APPS-2856 VideoEmbed Responsiveness

---

src/lib-components/NavBreadcrumb.vue
src/stories/NavBreadcrumb.stories.js

Connected to [APPS-2858](https://jira.library.ucla.edu/browse/APPS-2858)
**Component Updated:** NavBreadcrumb.vue
**Stories:** ~/stories/NavBreadcrumb.stories.js
**Note:**
- Remove last occurrence of date pattern (00-00-00) in URL/route string parsed to create breadcrumbs
- Test Route: `'/events/upcoming-events/la-région-centrale-10-20-23-screening-03-08-24' `
**Checklist:**
-   [x] I have requested a PR review from the dev team
-   [x] I assigned …

fix: APPS-2858 Remove Trailing Dates from NavBeadcrumbs

---

src/lib-components/MastheadSecondary.vue

Connected to [APPS-2825](https://jira.library.ucla.edu/browse/APPS-2825)
**Component Updated:** MastheadSecondary.vue
**Notes:**
- Shifting layout of MastheadSecondary sections in Vue3 (compared to Vue2) was being caused by additional margin emanating from the RichText component used in the Masthead:
- https://github.com/UCLALibrary/ucla-library-website-components/blob/1a3fe6d1255bf1e125fd629552c24d5a6d4721bd/src/lib-components/RichText.vue#L69
- Reset `margin-bottom` of the embedded RichText to `0` 
- https://deploy-preview-581--ucla-library-storybook.netlify.app/?path=/story/masthead-secondary--default
**Checklist:**
-   ~~[ ] I checked that it is working locally …

fix: APPS-2825 Fix MastheadSecondary Height

---

.storybook/main.ts
src/lib-components/BlockCardWithImage.vue
src/lib-components/BlockEventDetail.vue
src/lib-components/BlockInfo.vue
src/lib-components/BlockRemoveSearchFilter.vue
src/lib-components/BlockScreeningDetail.vue
src/lib-components/BlockTag.vue
src/lib-components/ButtonDropdown.vue
src/lib-components/ButtonLink.vue
src/lib-components/CardMeta.vue
src/lib-components/DateFilter.vue
src/lib-components/DividerWayFinder.vue
src/lib-components/Flexible/MediaGallery/NewLightbox.vue
src/lib-components/FooterLinks.vue
src/lib-components/FooterPrimary.vue
src/lib-components/FooterSock.vue
src/lib-components/NavBreadcrumb.vue
src/lib-components/NavSearch.vue
src/lib-components/SectionTeaserCard.vue
src/styles/_ftva-theme.scss
src/styles/default/_block-info.scss
src/styles/default/_block-screening-detail.scss
src/styles/ftva/_block-card-with-image.scss
src/styles/global.scss
vite.config.ts

Connected to [APPS-2867](https://jira.library.ucla.edu/browse/APPS-2867)
**Notes:**
When we implemented the theme pattern we introduced an anti-pattern that removed scoping (plus we are reloading the theme a lot which bloats the project). This has led to problems with styling, especially for the card-meta component which is reused as a child component in 4 other components (BlockCardWithImage, BlockClippedDate, BlockFloatingHighlight, SectionTeaserCard), in addition to being used directly on the page.
This PR:
- imports ONLY the components theme files, so that styles are once again scoped. 
- adds default theme files for a few components which didnt have them
- restores styles in SectionTeaserCard & BlockCardWithImage for ftva that were getting overwritten
**Checklist:**
-   [X] I checked …

chore: refactor theme pattern to rescope styles, add deep() where needed

---

src/lib-components/BlockHours.vue

Connected to [APPS-2852](https://jira.library.ucla.edu/browse/APPS-2852)
Using /blockHours.html is not working locally on Nuxt side in static mode
[APPS-2852]: https://uclalibrary.atlassian.net/browse/APPS-2852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add production url back for blockhours

---

src/lib-components/BlockHours.vue

Reverts UCLALibrary/ucla-library-website-components#593

fix: Revert "fix: Add production url back for blockhours"

---

src/lib-components/SectionWrapper.vue
src/stories/SectionWrapper.stories.js
src/styles/ftva/_section-wrapper.scss

Connected to [APPS-2918](https://jira.library.ucla.edu/browse/APPS-2918)
**Notes:**
Adds support for ftva theme to sectionwrapper, also adds paleblue theme and white theme variation for the background color work.
**Checklist:**
[APPS-2918]: https://uclalibrary.atlassian.net/browse/APPS-2918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

feat: Add ftva theme to sectionwrapper and paleblue theme to scss file

---

src/lib-components/DividerWayFinder.vue
src/lib-components/NavBreadcrumb.vue
src/stories/NavBreadcrumb.stories.js

Connected to [APPS-2914](https://jira.library.ucla.edu/browse/APPS-2914)
**Component Updated:** NavBreadcrumb.vue
**Notes:**
- 
**Checklist:**
-   ~[ ] UX has reviewed and approved this~
-   [x] I requested a PR review from the dev team
[APPS-2914]: https://uclalibrary.atlassian.net/browse/APPS-2914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: APPS-2914 NavBreadcrumb hydration error

---

src/lib-components/VideoEmbed.vue

Connected to [APPS-2926](https://jira.library.ucla.edu/browse/APPS-2926)
**Component Updated:** VideoEmbed.vue
**Local Nuxt screenshots:**
_Before_
<br>
_After_
**Checklist:**
-   [x] I have requested a PR review from the dev team
[APPS-2926]: https://uclalibrary.atlassian.net/browse/APPS-2926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: APPS-2926 VideoEmbed cover image sizing

---

src/lib-components/BlockEventDetail.vue
src/stories/BlockEventDetail.stories.js
src/utils/formatEventDates.js

Connected to [APPS-2941](https://jira.library.ucla.edu/browse/APPS-2941)
**Component Updated:** BlockEventDetail.vue
**Stories:** ~/stories/BlockEventDetail.stories.js
Added 2 stories for EventSeries data, one with date range, one with ongoing
**Checklist:**
-   [X] UX has reviewed and approved this
[APPS-2941]: https://uclalibrary.atlassian.net/browse/APPS-2941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

feat: APPS-2941 add enddate, ongoing props to blockeventdetail.vue

---

src/stories/SectionWrapper.stories.js
src/styles/ftva/_section-teaser-card.scss
src/styles/ftva/_section-wrapper.scss

Connected to [APPS-2937](https://jira.library.ucla.edu/browse/APPS-2937)
**Component Updated:** _section-teaser-card.scss
https://deploy-preview-610--ucla-library-storybook.netlify.app/?path=/story/section-wrapper--ftva-series-2-cards
**Screenshots:**
**Checklist:**
-   [x] I requested a PR review from the dev team
[APPS-2937]: https://uclalibrary.atlassian.net/browse/APPS-2937?atlOrigin=eyJpIjoiNWRkNTljNzYx …

fix: APP-2937 Remove gap between FTVA event cards

---

src/stories/HeaderSticky.stories.js
src/styles/ftva/_header-sticky.scss

**Notes:**
Prevents long menu items from overflowing the container. 
Discussed with UX here: https://uclalibrary.slack.com/archives/C014BPS0YBX/p1726169734734269
UX would like to make further changes to header styles, we need to make time next week or following. This is merely a quickfix to prevent the current 'broken' look.
**Checklist:**
-   [X] I added a screenshot of it working
-   [X] UX has reviewed and approved this
-   [X] I used a conventional …

fix: overflowing long text in ftva menu

---

src/lib-components/TabItem.vue
src/lib-components/TabList.vue
src/stories/TabToggle.stories.js
src/styles/default/_tab-list.scss

Connected to [APPS-2943](https://jira.library.ucla.edu/browse/APPS-2943)
**Component Updated:** TabList.vue
**Preview:** https://deploy-preview-611--ucla-library-storybook.netlify.app/?path=/story/tab-toggle--set-initial-tab
**Notes:**
- Added prop to allow initial active tab to be set
- Added extra story to demonstrate feature
- Updated/refactored tab glider animation
**Checklist:**
-   [x] I requested a PR review from the dev team
-   [x] I …

feat: APPS-2943 Add initialTab setting option to TabToggle

---

src/lib-components/TwoColLayoutWStickySideBar.vue

Connected to [APPS-2982](https://jira.library.ucla.edu/browse/APPS-2982)
**Component Created:** TwoColLayoutWStickySideBar.vue
**Notes:**
- Removed padding to the left and right of the component.
**Before:**
**After:**
**Checklist:**
[APPS-2982]: https://uclalibrary.atlassian.net/browse/APPS-2982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …

fix: APPS-2982 Remove excess padding values

---

src/styles/ftva/_section-teaser-card.scss

Connected to [APPS-2962](https://jira.library.ucla.edu/browse/APPS-2962)
**Notes:**
When section teaser card has 3 cards we'd like the third card to align with the edge of the link.
When section teaser card has fewer cards, we'd like the cards to align one after another without big gaps in between. 
This PR adds styles for 3 cards to justify content to the edges, but will not change the styles for 2 cards. We do bump the gap for 2 cards to 20px minimum so that it will not ever look too different than the responsive gap between the 3 card layouts, regardless of screen size
**Checklist:**
library-website-nuxt dev …

chore: APPS-2962 move styles from page to story

---

src/styles/ftva/_section-teaser-card.scss

Connected to [APPS-2687](https://jira.library.ucla.edu/browse/APPS-2687)
**Notes:**
Quick ticket to add styles to component for ftva that are currently duplicated on every page.
Ticket specifies .is-vertical class but SectionTeaserCard is set to always use is-vertical so this seemed redundant to me, so I just added it to the scoped styles for card inside section-teaser-card
**Checklist:**
- …

chore: APPS-2992 move min height styles to sectionTeaserCard

---

src/lib-components/Flexible/MediaGallery.vue
src/lib-components/Flexible/MediaGallery/BannerImage.vue
src/lib-components/Flexible/MediaGallery/NewLightbox.vue
src/lib-components/Flexible/MediaGallery/ThumbnailCard.vue
src/lib-components/MediaBadge.vue
src/stories/Flexible_MediaGallery.stories.js
src/stories/MediaBadge.stories.js
src/stories/MediaGallery_BannerImage.stories.js
src/stories/MediaGallery_NewLightbox.stories.js
src/stories/MediaGallery_ThumbnailCard.stories.js
src/stories/mock/FTVAMedia.js
src/styles/default/_media-badge.scss
src/styles/default/_media-gallery-banner-image.scss
src/styles/default/_media-gallery-thumbnail-card.scss
src/styles/default/_media-gallery.scss
src/styles/ftva/_media-badge.scss
src/styles/ftva/_media-gallery-banner-image.scss
src/styles/ftva/_media-gallery-thumbnail-card.scss
src/styles/ftva/_media-gallery.scss
src/styles/ftva/_new-lightbox.scss

Connected to [APPS-2959](https://jira.library.ucla.edu/browse/APPS-2959)
**Components Updated:**
- MediaBadge.vue
- ~/Flexible/MediaGallery.vue
- ~/Flexible/MediaGallery/BannerImage.vue
- ~/Flexible/MediaGallery/NewLightbox.vue
- ~/Flexible/MediaGallery/ThumbnailCard.vue
**Stories:**
- ~/stories/MediaBadge.stories.js
- ~/stories/MediaGallery_BannerImage.stories.js
- ~/stories/MediaGallery_NewLightbox.stories.js
- ~/stories/MediaGallery_ThumbnailCard.stories.js
- ~/stories/Flexible_MediaGallery.stories.js
<br>
**Notes:**
- Updated multiple components that comprise the FlexibleMediaGallery with FTVA variants
- Added new prop `inline` to be used to set the Lightbox component to display as an inline component, preserving the default overlay behavior when needed
- Any FTVA template currently …

feat: APPS-2959 FlexibleMediaGallery FTVA variant

---

src/lib-components/BlockCardThreeColumn.vue

Connected to [APPS-3001](https://jira.library.ucla.edu/browse/APPS-3001)
**Notes:**
We add position:relative to force the link element onto the card it belongs to, instead of it floating on top of the top card in the list!
Also removed some extra li styles as directed in the ticket 
**Checklist:**
[APPS-3001]: …

fix: add relative position to anchor link on card

---

src/lib-components/ButtonDropdown.vue
src/styles/default/_button-dropdown.scss
src/styles/ftva/_button-dropdown.scss

Connected to [APPS-2984](https://jira.library.ucla.edu/browse/APPS-)
**Component Updated:** ButtonDropdown.vue
**Notes:**
- Update component to make button drop down over content rather than shift content downwards
**Storybook Previews:**
- Calendar button
- https://deploy-preview-631--ucla-library-storybook.netlify.app/?path=/story/layout-2-column-layout-with-sticky-sidebar--ftva-event-detail
- Share button
- https://deploy-preview-631--ucla-library-storybook.netlify.app/?path=/story/layout-2-column-layout-with-sticky-sidebar--ftva-blog-detail
<br>
**Local Nuxt Previews:**
- *Calendar Dropdown*
- *Share Dropdown*
<br>
**Checklist:**
-   [x] I checked that it is …

fix: APPS-2984 Share/Calendar button dropdown behavior

---

src/lib-components/TwoColLayoutWStickySideBar.vue

Connected to [APPS-2983](https://jira.library.ucla.edu/browse/APPS-2983)
**Component Updated:** TwoColLayoutWithStickySidebar.vue
**Notes:**
- Set fixed width value for sidebar column in two-column layout component
- Removed excess padding on component
**Local Nuxt Previews:**
_Desktop_
<br>
_Tablet_
<br>
_Mobile_
<br>
_Fixed excess padding_
<br>
**Checklist:** …

fix: APPS-2983 Add fixed-width value to sidebar column

---

src/lib-components/BlockCardThreeColumn.vue
src/styles/ftva/_block-card-with-image.scss
src/styles/ftva/_rich-text.scss

Connected to [APPS-2969](https://jira.library.ucla.edu/browse/APPS-2969)
**Components Updated:** 
- BlockCardThreeColumn.vue
- BlockCardWithImage.vue
- RichText.vue
**Notes:**
- updated CSS to add hover state to FTVA horizontal cards in BlockCardThreeColumn
- updated hover color for FTVA RichText to `$bright-blue` per UX (re [Slack thread](https://uclalibrary.slack.com/archives/C014BPS0YBX/p1729101841687409))
- removed redundant style rule in FTVA BlockCardWithImage
**Previews:**
- https://deploy-preview-633--ucla-library-storybook.netlify.app/?path=/story/global-rich-text--ftva-rich-text
- https://deploy-preview-633--ucla-library-storybook.netlify.app/?path=/story/section-teaser-list--dynamic-component
**Checklist:**
-   [x] …

fix: APPS-2969 Add hover state to FTVA card-horizontal titles

---

src/lib-components/BlockCallToAction.vue
src/styles/default/_block-call-to-action.scss
src/styles/ftva/_block-call-to-action.scss

Connected to [APPS-3007](https://jira.library.ucla.edu/browse/APPS-3007)
**Component Created:** BlockCallToAction.vue
**Notes:**
- Replaced use of parsed-text-handlebar template with RichText component
- Updated CSS
- [Update to FTVA variant of RichText](https://github.com/UCLALibrary/ucla-library-website-components/pull/633) should show linked text with thicker pale blue underline that turns bright blue on hover 
<br>
**Preview:**
- https://deploy-preview-634--ucla-library-storybook.netlify.app/?path=/story/block-call-to-action--ftva-slim-cta-titled
<br>
**Checklist:**
-   [x] I …

fix: APPS-3007 Use RichText comp in BlockCTA comp

---

src/styles/ftva/_block-screening-detail.scss

Connected to [APPS-2889](https://jira.library.ucla.edu/browse/APPS-2889)
**Component Styles Updated:** /ftva/_block-screening-detail.scss
**Notes:**
Some of the styles were missed on the first pass through, we are updating them to match the mockups https://www.figma.com/design/L8e1czKo8a8px368ayyPZ4/%5BFTVA%5D-Final-Design-with-Annotations?node-id=1422-31472&node-type=frame&t=FWW5UFCw30U3kQwl-0
Before:
After:
**Checklist:**
-   [X] I added a screenshot of it working
-   [X] UX has reviewed and approved this
-   [X] I …

fix: APPS-2889 styles for screening text

---

src/lib-components/TwoColLayoutWStickySideBar.vue

Connected to [APPS-3030](https://jira.library.ucla.edu/browse/APPS-3030)
**Component Updated:** TwoColLayoutWStickySidebar.vue
**Notes:**
- Added space/margin to the right of the sidebar column at tablet resolution
- Shifted the component to one-column at earlier breakpoint 
https://deploy-preview-644--ucla-library-storybook.netlify.app/?path=/story/layout-2-column-layout-with-sticky-sidebar--event-series
**Checklist:**
-   [x] I used a conventional …

fix: APPS-3030 Adjust TwoColumn component spacing

---

src/lib-components/TwoColLayoutWStickySideBar.vue

Connected to [APPS-3041](https://jira.library.ucla.edu/browse/APPS-3041)
**Component Created:** TwoColLayoutWStickySidebar.vue
**Notes:**
- Reset primary column width at updated tablet breakpoint range
**Checklist:**
-   [x] I assigned this PR to someone on the dev team to review~~
-   [x] I used a conventional commit message~~
-   [x] I assigned myself to this PR~~
[APPS-3041]: https://uclalibrary.atlassian.net/browse/APPS-3041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

fix: APPS-3041 Reset TwoCol component primary column width

---

src/styles/default/_block-call-to-action.scss

Connected to [APPS-3046](https://jira.library.ucla.edu/browse/APPS-3046)
**Component Updated:** BlockCallToAction.vue
**Notes:**
- Removed excess spacing below SlimCTA text content--coming from RichText component's `parsed-content` class
- Setting `parsed-content`'s margin-bottom to 0 in the default file does not affect spacing in the default component; `text` div that is parent to `parsed-content` already has a margin-bottom value of 32px (which takes precedence over `parsed-content`'s 28px value)
https://deploy-preview-648--ucla-library-storybook.netlify.app/?path=/story/block-call-to-action--ftva-slim-cta-titled
*Before*
*After*
**Checklist:**
-   [x] I checked …

fix: APPS-3046 Remove excess content spacing in SlimBlockCTA

---

.github/workflows/publish-to-npm.yml

this fixes the following bug:
https://github.com/UCLALibrary/ucla-library-website-components/actions/runs/11694891777/job/32569373589
```
Run pnpm install
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
Your pnpm version is incompatible with "/home/runner/work/ucla-library-website-components/ucla-library-website-components".
Expected version: ^9.12.1
Got: [8](https://github.com/UCLALibrary/ucla-library-website-components/actions/runs/11694891777/job/32569373589#step:5:9).15.9
This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.
To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
Error: Process completed …
```

feat: fix pnpm version in publish action

---

src/lib-components/SectionPagination.vue
src/stories/SectionPagination.stories.js

Connected to [APPS-3074](https://jira.library.ucla.edu/browse/APPS-3074)
**Component Edited:** SectionPagination.vue
**Stories Updated:** ~/stories/SectionPagination.stories.js
**Notes:**
@pghorpade noticed during implementation in the FTVA project that the `SectionPagination.vue` component was not mounting correctly. 
Upon investigation, this was because we only use the props `pages` & ` initialCurrentPage` on initialization of the component, not in the render template itself. This PR fixes that.
No visual changes were made
**Checklist:**
-   [X] I added a screenshot of it working …

fix: APPS-3074 add watchers for pagination reactivity

---

src/lib-components/ButtonDropdown.vue
src/lib-components/DateFilter.vue
src/lib-components/MobileDrawer.vue
src/stories/DateFilter.stories.js
src/stories/MobileDrawer.spec.js
src/stories/MobileDrawer.stories.js
src/styles/default/_button-dropdown.scss
src/styles/default/_mobile-drawer.scss
src/styles/ftva/_button-dropdown.scss
src/styles/ftva/_mobile-drawer.scss

Connected to [APPS-3045](https://jira.library.ucla.edu/browse/APPS-3045)
**Component Created:** MobileDrawer.vue
**Stories:** ~/stories/MobileDrawer.stories.js
**Spec:** ~/stories/MobileDrawer.spec.js
**Notes:**
Work done:
Not done:
*factor <VueDatePicker> component into its own file*
DateFilter.vue had to be duplicated in the template to get it to fit into our mobile designs (it shows in one spot if we are on mobile, a different spot if we aren't). 
To prevent duplicating the code, I had wanted to refactor our implementation to put the <VueDatePicker> code in its own component, thus making it easier/shorter to duplicate that component. However, I stopped because the MobileDrawer component needs to pass a removeOverlay method to a specific button on the VueDatePicker to allow it to close …

feat: APPS-3045 refactor mobile drawer, datefilter mobile

---

pnpm-lock.yaml
src/lib-components/TabList.vue
src/stories/TabToggle.stories.js

Connected to [APPS-3080](https://jira.library.ucla.edu/browse/APPS-3080),  [APPS-3077](https://jira.library.ucla.edu/browse/APPS-3077)
**Component Updated:** TabList.vue
**Notes:**
- Update TabList code to make tab buttons SEO friendly
- Add dynamic routing to update browser URL without reloading the page
- Detect the active tab from the URL
**Checklist:**
-   ~~[ ] I checked that it is working locally in the storybook~~
-   [x] I assigned …

fix: APPS 3080 Update TabList buttons with SEO logic

---

src/lib-components/DateFilter.vue
src/lib-components/FiltersDropdown.vue
src/styles/default/_filters-dropdown.scss
src/styles/default/_mobile-drawer.scss
src/styles/ftva/_filters-dropdown.scss

Connected to [APPS-3112](https://jira.library.ucla.edu/browse/APPS-3112)
**Notes:**
When implementing filters side by side on event listing page we noticed style differences. This PR will unify the styles between the 2.
**Checklist:**
[APPS-3112]: https://uclalibrary.atlassian.net/browse/APPS-3112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …

chore: APPS-3112 unify styles between datefilter and filterdropdown

---

README.md
src/lib-components/TabList.vue

Connected to [APPS-3115](https://jira.library.ucla.edu/browse/APPS-3115)
**Component updated:** TabList.vue
**Notes:**
Add an important information of the pull request labels to use in the Read Me file , also reset page to 1 when switching between tabs.
[APPS-3115]: https://uclalibrary.atlassian.net/browse/APPS-3115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update readme with pr labels to use, and reset page number

---

src/styles/default/_rich-text.scss

Connected to [APPS-3042](https://jira.library.ucla.edu/browse/APPS-3042)
**Component Created:** RichText.vue
**Notes:**
- Updated the height setting for iframe videos embedded in RichText to preserve their height
**Local Nuxt Previews:**
*Before:*
*After:*
**Checklist:**
[APPS-3042]: https://uclalibrary.atlassian.net/browse/APPS-3042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …

fix: APPS-3042 Embedded video height in RichText

---

src/styles/default/_button-dropdown.scss

Connected to [APPS-3043](https://jira.library.ucla.edu/browse/APPS-3043)
**Component Updated:** ButtonDropdown.vue
**Notes:**
- Fixed page/rich-text content overlaying on top of share button dropdown links
**Local Nuxt Previews:**
**Checklist:**
[APPS-3043]: https://uclalibrary.atlassian.net/browse/APPS-3043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

fix: APPS-3043 Add z-index to dropdown button

---

src/lib-components/TabList.vue

Connected to [APPS-3118](https://jira.library.ucla.edu/browse/APPS-3118)
**Component updated:** TabList.vue
When refactoring the duplicate scrolling and moving the sticky on tablist we saw this warning in console
[Vue warn]: Extraneous non-props attributes (class) were applied to component but could not be automatically inherited because component renders multiple root nodes.
https://vuejs.org/guide/components/attrs#attribute-inheritance-on-multiple-root-nodes
[APPS-3118]: https://uclalibrary.atlassian.net/browse/APPS-3118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add attribute inheritance when component has multiple root nodes

---

src/lib-components/BlockCardWithImage.vue
src/lib-components/BlockStaffSubjectLibrarian.vue
src/lib-components/CardMeta.vue
src/stories/BlockCardWithImage.stories.js
src/stories/CardMeta.stories.js

Connected to [APPS-3158](https://jira.library.ucla.edu/browse/APPS-3158)
**Component Updated:** cardmeta.vue and blockcardwithimage.vue
**Stories:** ~/stories/cardmeta.stories.js and blockcardwithimage.stories.js
**Notes:**
Rename slot names , this will effect page template. Also added conditional slots check to blockcardwithimage
[APPS-3158]: https://uclalibrary.atlassian.net/browse/APPS-3158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add conditional slots to blockcardwithimage template

---

package.json
pnpm-lock.yaml
src/lib-components/BlockCardWithImage.vue
src/lib-components/ResponsiveImage.vue
src/lib-components/SectionTeaserCard.vue
src/stories/BlockCardWithImage.stories.js
src/stories/ResponsiveImage.stories.js
src/stories/SectionTeaserCard.stories.js
src/styles/default/_section-teaser-card.scss
src/styles/ftva/_section-teaser-card.scss
src/types/types.ts

Connected to [APPS-3165](https://jira.library.ucla.edu/browse/APPS-3165)
**Notes:**
- I added a slot to the `ResponsiveImage` component to allow us to put content in the top right corner of an image, similar to the credit slot we already have.
- I implemented a story for ResponsiveImage using the new slot
- I added a slot with the same name to BlockCardWithImage to allow us to pass this slot through that component
- I implemented a story for BlockCardWithImage using the new slot
- Lastly, I added some logic to SectionTeaserCard to allow it to display FTVACollectionItems with a 'Video' BlockTag when the item has a VideoEmbed field
**Checklist:**
-   [X] I checked …

feat: APPS-3165 Update SectionTeaserCard & BlockCardWIthImage for Collection Item page

---

src/lib-components/Flexible/ImpactNumberCards.vue
src/lib-components/ImpactNumberCard.vue
src/stories/Flexible_ImpactNumberCards.stories.js
src/stories/ImpactNumberCard.stories.js
src/styles/default/_impact-number-card.scss
src/styles/default/_impact-number-cards.scss
src/styles/ftva/_impact-number-card.scss
src/styles/ftva/_impact-number-cards.scss

Connected to [APPS-3150](https://jira.library.ucla.edu/browse/APPS-3150)
**Component Updated:** ImpactNumberCard.vue, ImpactNumberCards.vue
**Stories:** ~/stories/ImpactNumberCard.stories.js, ~/stories/Flexible_ImpactNumberCards.stories.js
**Notes:**
**Checklist:**
-   [X] I added a screenshot of it working
-   [X] UX has reviewed and approved this
[APPS-3150]: https://uclalibrary.atlassian.net/browse/APPS-3150?atlOrigin=eyJpIjoiNWRkNTljNzY …

feat: APPS-3150 add ftva theme to Flexible ImpactNumberCards

---

packages/vue-component-library/release.config.cjs

Connected to [APPS-3134](https://jira.library.ucla.edu/browse/APPS-3134)
```
Error: semantic-release-monorepo: Incorrect plugin name type. Expected string but was {"releaseRules":[{"type":"refactor","release":"patch"},{"type":"chore","release":"patch"}]}.
at semantic-release-monorepo
```
[APPS-3134]: https://uclalibrary.atlassian.net/browse/APPS-3134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: release config error

---

packages/vue-component-library/src/styles/ftva/_block-info.scss

Connected to [APPS-3231](https://jira.library.ucla.edu/browse/APPS-3231)
**Component Updated:** BlockInfo.vue
**Notes:**
- Deleted styles that have been moved to the page level
**Checklist:**
-   [x] I have requested a PR review from the Dev team
[APPS-3231]: https://uclalibrary.atlassian.net/browse/APPS-3231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: APPS-3231 Delete BlockInfo styles moved to page-level

---

packages/vue-component-library/src/lib-components/Flexible/MediaWithText.vue

Connected to [APPS-3247](https://jira.library.ucla.edu/browse/APPS-3247)
**Component Updated:** /Flexible/MediaWithText.vue
**Notes:**
- Add missing import statement for DividerGeneral component
**Before:** https://deploy-preview-707--ucla-library-storybook.netlify.app/?path=/docs/flexible-media-with-text--docs
**After:** https://deploy-preview-708--ucla-library-storybook.netlify.app/?path=/docs/flexible-media-with-text--docs
**Checklist:**
-   [x] I have requested a PR review from …

fix: APPS-3247 Add FlexibleMediaText's missing Divider import

---

packages/vue-component-library/src/lib-components/FlexibleBlocks.vue
packages/vue-component-library/src/styles/ftva/_section-wrapper.scss

Connected to [APPS-3260](https://jira.library.ucla.edu/browse/APPS-3260)
**Component Updated:** SectionWrapper.vue styles
**Notes:**
The ticket specified these styles at the `SectionWrapper` level however that will not work because we do not want SectionWrappers to have bold titles outside of `FlexibleBlock` components (confirmed by @tieserena in this [slack thread](https://uclalibrary.slack.com/archives/C014BPS0YBX/p1742406743756219)) - so they have been added to FlexibleBlock instead
**Checklist:**
-   [X] UX has reviewed and approved …

feat: add section-title and section-summary

---

packages/vue-component-library/src/stories/PageAnchor.stories.js
packages/vue-component-library/src/styles/ftva/_page-anchor.scss

Connected to [APPS-3263](https://jira.library.ucla.edu/browse/APPS-3263)
**Component Updated:** PageAnchor.vue
**Notes:**
- Updated positioning of FTVA anchor
- Adjusted alignment of icon/caret
- Updated/tested story with a longer title
**Preview:** https://deploy-preview-711--ucla-library-storybook.netlify.app/?path=/story/pageanchor--ftva-theme
**Local Nuxt previews:**
- Before
<br>
- After
<br>
**Checklist:**
-   [x] I used a conventional …

fix: APPS-3263 Fix FTVA PageAnchor alignment

---

packages/vue-component-library/vite.config.ts

Connected to [APPS-3281](https://jira.library.ucla.edu/browse/APPS-3281)
When I enabled svg optimization in vite.config.ts in this PR https://github.com/UCLALibrary/ucla-library-website-components/pull/710
The ftva main footer UCLA library image was hidden and we could only see a white rectangular box in storybook and on the ftva pages 
old: https://deploy-preview-710--ucla-library-storybook.netlify.app/?path=/story/footer-main--ftva-footer
fixed in this PR: https://deploy-preview-717--ucla-library-storybook.netlify.app/?path=/story/footer-main--ftva-footer
[APPS-3281]: https://uclalibrary.atlassian.net/browse/APPS-3281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: revert svgo changes

---

packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue

Connected to [APPS-2314](https://jira.library.ucla.edu/browse/APPS-2314)
if the selectedprop is empty also reset selectedletter data in the component to empty string
[APPS-2314]: https://uclalibrary.atlassian.net/browse/APPS-2314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: selcted letter needs to reset to empty string after the filter is removed from search-generic search filters

---

packages/vue-component-library/src/lib-components/SearchResult.vue
packages/vue-component-library/src/stories/SearchResult.stories.js

Connected to [APPS-2576](https://jira.library.ucla.edu/browse/APPS-2576)
**Component Created:** SearchResults.vue
**Stories:** ~/stories/SearchResults.stories.js
**Notes:**
This component currently does not use rich text for summary content, and also HTML is stripped out and is truncated
https://deploy-preview-722--ucla-library-storybook.netlify.app/?path=/story/search-search-result--event-item
https://deploy-preview-722--ucla-library-storybook.netlify.app/?path=/story/search-search-result--event-series-ongoing
https://deploy-preview-722--ucla-library-storybook.netlify.app/?path=/story/search-search-result--event-series
[APPS-2576]: https://uclalibrary.atlassian.net/browse/APPS-2576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add slots to SearchResults.vue to support new requirement to show date time for events, series and workshops after title

---

packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue
packages/vue-component-library/src/styles/default/_alphabetical-browse-by.scss
packages/vue-component-library/src/styles/ftva/_alphabetical-browse-by.scss

Connected to [APPS-3309](https://jira.library.ucla.edu/browse/APPS-3309)
**Component Updated:** AlphabeticalBrowseBy.vue
**Stories:** ~/stories/AlphabeticalBrowseBy.stories.js
**Notes:**
- Moved styles out of script and template code
- Add stylesheet and styles for FTVA
**Preview:**
- https://deploy-preview-727--ucla-library-storybook.netlify.app/?path=/story/search-alphabeticalbrowseby--ftva
**Local Nuxt preview:**
**Checklist:**
-   [x] I used a …

feat: APPS-3309 Update AlphabeticalBrowseBy with FTVA variant

---

packages/vue-component-library/src/lib-components/AlphabeticalBrowseBy.vue
packages/vue-component-library/src/lib-components/SectionPostSmall.vue
packages/vue-component-library/src/stories/AlphabeticalBrowseBy.stories.js

@tinuola Reported the following bug
Another question on my ticket. When a letter is clicked, it is highlighted. However, when the same query is pasted, 'All' is highlighted and then clicking another letter right after shows 'All' and the new letter. The strange thing is this is only happening in the deploy/preview environment. Not locally. I've tried a few different tweaks to the logic, but no change in the deploy env.
This PR will fix the above mentioned issue and the hydration issue with setionpostsmall component

feat: fix hydration issue with sectionpostsmall and have single source of truth and refactor to script setup AlphabeticalBrowseBy component

---

packages/vue-component-library/src/lib-components/SearchGenericFilters.vue

fix: reset querydropdownqueryFilterButtonDropDownStates when newQueryFilters is empty

---

packages/vue-component-library/src/lib-components/Flexible/MediaGallery/NewLightbox.vue
packages/vue-component-library/src/stories/Flexible_MediaGallery.spec.js
packages/vue-component-library/src/stories/MediaGallery_NewLightbox.stories.js
packages/vue-component-library/src/stories/mock/FTVAMedia.js
packages/vue-component-library/src/styles/ftva/_new-lightbox.scss

Connected to [APPS-2805](https://jira.library.ucla.edu/browse/APPS-2805)
**Component Updated:** NewLightbox.vue
**Notes:**
- Set up/updated inline Lightbox/carousel styling for FTVA homepage
- Added logic to code to set/control placement of carousel navigation arrows
- Added mock data for carousel
- Updated carousel story
- Included helper functions to parse data (_[similar] helpers will need to be replicated at page level_)
**Preview:**
- https://deploy-preview-748--ucla-library-storybook.netlify.app/?path=/story/media-gallery-new-lightbox--ftva-homepage-carousel
**Checklist:**
-   ~~[ ] I checked that it is working locally in the library/ftva-website-nuxt dev …

feat: APPS-2805 Update Lightbox Theme for FTVA Homepage

---

packages/vue-component-library/src/styles/ftva/_new-lightbox.scss

Connected to [APPS-3379](https://jira.library.ucla.edu/browse/APPS-3379)
**Component Updated:** NewLightbox.vue
**Notes:**
- Fix for a layout issue detected when implementing component on Nuxt site: in mobile view, carousel data is trapped in a scroll box
- Tested change locally
**Preview:**
- Before: https://deploy-preview-748--ucla-library-storybook.netlify.app/?path=/story/media-gallery-new-lightbox--ftva-homepage-carousel
- After: https://deploy-preview-753--ucla-library-storybook.netlify.app/?path=/story/media-gallery-new-lightbox--ftva-homepage-carousel
**Local Screenshots:**
- Before
- After
**Checklist:**
-   [x] I checked that it is working locally in …

fix: APPS-3379 Fix FTVA Homepage Carousel mobile layout

---

packages/vue-component-library/src/index.ts
packages/vue-component-library/src/lib-components/ImageSlider.vue
packages/vue-component-library/src/stories/ImageSlider.spec.js
packages/vue-component-library/src/stories/ImageSlider.stories.js

Connected to [APPS-3376](https://jira.library.ucla.edu/browse/APPS-3376)
**Component Created:** imageSlider.vue
**Stories:** ~/stories/imageSlider.stories.js
**Spec:** ~/stories/imageSlider.spec.js
**Notes:**
- I had originally used a slightly different solution for the slider, but it didn't work on sliders that needed to be rectangular rather and square. So I rewrote the styles to be more responsive and make use of `clip-path` property.
- Slots were added for Before & After label text and the caption
- I started scaffolding out a story with a ScrollWrapper carousel, but ultimately carousel work was split off into a separate ticket 
**Checklist:**
-   [X] I checked …

feat: APPS-3376 create image slider component

---

packages/vue-component-library/src/lib-components/Flexible/MediaWithText.vue
packages/vue-component-library/src/stories/BlockMediaWithText.stories.js
packages/vue-component-library/src/stories/mock/BlockMediaWithText.js
packages/vue-component-library/src/stories/mock/FTVAMedia.js
packages/vue-component-library/src/stories/mock/Flexible_MediaWithText.js

Connected to [APPS-3358](https://jira.library.ucla.edu/browse/APPS-3358)
**Component Updated:** Flexible/MediaWithText.vue
**Storybook Previews:**
- No regressions
- https://deploy-preview-755--ucla-library-storybook.netlify.app/?path=/story/flexible-media-with-text--ftva-default
- https://deploy-preview-755--ucla-library-storybook.netlify.app/?path=/story/flexible-blocks--ftva-flexible-blocks
**Notes:**
- In Craft, if `other` was selected as a media type in the FlexibleMediaWithText block the page would break/error out; [see ticket for screenshots](https://jira.library.ucla.edu/browse/APPS-3358)
- Fix: Added null check to block content parsing in FlexibleMediawithText
- Updated mock data and stories with additional [missing] fields for testing
- Tested against updated Craft data and …

fix: APPS-3358 Fix typeMedia parsing error in FlexMediaWithText

---

packages/vue-component-library/src/lib-components/FiltersDropdown.vue

Connected to [APPS-3185](https://jira.library.ucla.edu/browse/APPS-3185)
**Component Updated:** FiltersDropdown.vue
**Notes:**
- Fixed `clear` button event handler to emit emptied filters object to parent
**Previews:**
- Before: https://deploy-preview-755--ucla-library-storybook.netlify.app/?path=/story/filters-dropdown--ftva-filters-update-done-click
- Select `clear` button
- Even though labels are toggled/deselected the `Selected filters display` object is still populated with the filters
- After: https://deploy-preview-756--ucla-library-storybook.netlify.app/?path=/story/filters-dropdown--ftva-filters-update-done-click
- Select `clear` button 
- `Selected filters display` object is emptied
**Local:**
https://github.com/user-attachments/assets/724ec7d0-1d66-4998-b675-14b5adb7f30b …

fix: clear filters when clear btn is clicked

---

packages/vue-component-library/src/stories/HeaderSticky.stories.js
packages/vue-component-library/src/styles/ftva/_nav-primary.scss

Connected to [APPS-3346](https://jira.library.ucla.edu/browse/APPS-3346)
**Component Created:** no component created, only changes to ftva SCSS added ~/src/styles/ftva/_nav-primary.scss
**Stories:** ~/stories/HeaderSticky.stories.js
**Spec:** ~/stories/HeaderSticky.spec.js
**Notes:**
The previous PR related to APPS-3346 did not take into account how mobile would be impacted by the changes. This PR allows for the mobile/small screen size to behave as expected when the nav-bar is expanded by adding `position: relative` as a property in the mobile SCSS. The stories have also been updated to remove nav-bar when the screen is small. 
**Preview:**
https://deploy-preview-761--ucla-library-storybook.netlify.app/?path=/story/global-header-sticky--ftva-sticky
**Photos** 
Before Stories: 
After …

fix:  APPS-3346 navbar reacts properly when screen size is small

---

packages/vue-component-library/src/stories/BlockStaffArticleList.stories.js
packages/vue-component-library/src/styles/ftva/_block-staff-article-item.scss

Connected to ~~[APPS-3031](https://jira.library.ucla.edu/browse/APPS-3031)~~ [APPS-3210](https://jira.library.ucla.edu/browse/APPS-3210)
**Component Created:** no components created only changed SCSS _block-staff-article-item.scss
**Stories:** ~/stories/blockStaffArticleList.stories.js
**Spec:** ~/stories/blocStaffArticleList.spec.js
**Notes:**
The font-size and color properties for the category were added to the FTVA-specific SCSS file. 
**Preview:** 
https://deploy-preview-764--ucla-library-storybook.netlify.app/?path=/story/block-staff-article-list--ftva-category
**Screenshots:**
Before:
After: 
**Checklist:**
-   [x] I checked that it is working locally in the …

fix: APPS-3031 Update category color and font-size for staff-article-list

---

packages/vue-component-library/src/styles/ftva/_mobile-drawer.scss

Connected to [APPS-3324](https://jira.library.ucla.edu/browse/APPS-3324)
**Component Edited:**ftva/ _mobile-drawer.scss
**Stories:** ~/stories/MobileDrawer.stories.js
**Spec:** ~/stories/MobileDrawer.spec.js
**Notes:**
Various scss properties were added to get the button to expand properly. The width comes from the width set for the "Share" button itself. 
**Photos:** 
Before:
After: 
**Link:**
https://deploy-preview-769--ucla-library-storybook.netlify.app/?path=/story/button-dropdown--ftva-share
**Checklist:**
-   [x] UX has reviewed and …

fix: APPS-3324 dropdown matches width of share button

---

packages/vue-component-library/src/stories/mock/CalendarEvents.js
packages/vue-component-library/src/styles/default/_base-calendar.scss
packages/vue-component-library/src/styles/ftva/_base-calendar.scss

Connected to [APPS-3198](https://jira.library.ucla.edu/browse/APPS-3198)
**Component Updated:** /styles/ftva/base-calendar.scss
**Notes:**
The border radius for calendar events in vuetify is 4px. These styles were clashing with our styles, so they have been overwritten at the calendar event level. 
Additionally, a border radius was applied to media elements that wasn't present with the placeholder image was used instead. Our stories only used placeholder images. I added images to the calendar story with events so any discrepancies will be easier to notice in the future.
**Checklist:**
library-website-nuxt dev …

fix: APPS-3198 border-radius calendar events

---

.github/workflows/ci.yml

Connected to [APPS-3404](https://jira.library.ucla.edu/browse/APPS-3404)
This PR updates the `Run CI Suite` workflow to:
- Separate Storybook build, deploy, and Cypress test steps for **internal PRs**, **forked PRs**, and **merged branches**.
- Introduce a **protected Netlify preview environment** for forked PRs, requiring manual approval from maintainers before secrets are exposed.
- Keep internal PR previews running automatically without approval.
- Build Storybook only once per run and share the artifact across deploy/test jobs to reduce redundancy.
---
1. **Storybook Build Job**
- Builds Storybook once.
- Uploads the static build as an artifact.
- Makes artifact available for all deploy/test jobs.
2. **Deploy Jobs**
- **Merged Deploy (`main` / `vue3.x`)** → Deploys to production …

fix: for forked PR's

---

packages/vue-component-library/src/lib-components/SectionStaffArticleList.vue
packages/vue-component-library/src/lib-components/SiteBrandBar.vue

Connected to [APPS-3399](https://jira.library.ucla.edu/browse/APPS-3399)
**Component Created:** siteBrandBar.vue
**Stories:** ~/stories/siteBrandBar..stories.js
**Spec:** ~/stories/siteBrandBar..spec.js
**Notes:**
For the FTVA theme the brand will now route to '/' or whatever the local homepage is
**Links:**
https://deploy-preview-793--ucla-library-storybook.netlify.app/?path=/story/global-site-brand-bar--ftva-version
**Checklist:**
- …

fix: APPS-3399 make sitebrand route to correct URL for ftva

---

packages/vue-component-library/src/lib-components/NavSearch.vue

Connected to [APPS-3396](https://jira.library.ucla.edu/browse/APPS-3396)
**Component Created:** NavSearch.vue
**Stories:** ~/stories/NavSearch.stories.js
**Spec:** ~/stories/NavSearch.spec.js
**Photos:**
Before:
After:
**Links:**
https://deploy-preview-812--ucla-library-storybook.netlify.app/?path=/story/nav-search--ftva
**Checklist:**
[APPS-3396]: …

fix: APPS-3396 change text below search bar

---

packages/vue-component-library/src/styles/ftva/_block-card-with-image.scss

Connected to [APPS-3208](https://jira.library.ucla.edu/browse/APPS-3208)
**Component Created:** blockCardWithImage.vue
**Stories:** ~/stories/blockCardWithImage.stories.js
**Spec:** ~/stories/blockCardWithImage.spec.js
**Notes:**
The `position: relative` for the CardMeta component was causing issues with the default clickablitiy behavior already established by the default .scss file in blockCardWithImage. Removal of it doesn't affect any other part of the card.
**Links:** 
https://deploy-preview-811--ucla-library-storybook.netlify.app/?path=/story/block-card-with-image--ftva-article-blog-listing
**Checklist:**
-   [x] I checked that it is working locally in the …

fix: APPS-3208 make block card with image clickable

---

packages/vue-component-library/src/styles/default/_base-calendar.scss
packages/vue-component-library/src/styles/ftva/_base-calendar.scss

Connected to [APPS-3193](https://jira.library.ucla.edu/browse/APPS-3193)
**Component Created:** _base-calendar.scss
**Stories:** ~BaseCalendars.stories.js
**Spec:** ~/stories/BaseCalendars.spec.js
**Photos:**
Before:
After: 
**Notes:**
The buttons needs to be 20 px away from the edge of the calendar.
**Checklist:**
[APPS-3193]: …

fix: APPS-3193 make arrows on calendar 20 pixels from calendar edges

---

packages/vue-component-library/src/styles/default/_nav-menu-item.scss

Connected to [APPS-3395](https://jira.library.ucla.edu/browse/APPS-3395)
**Component Created:** navMenuItem.vue
**Stories:** ~/stories/HeaderSticky.stories.js
~/stories/NavPrimary.stories.js
**Spec:** ~/stories/HeaderSticky.spec.js
~/stories/NavPrimary.spec.js
**Notes:**
The underline on a specific item was occuring any time the state of the specific item in the nav bar was active. This is only activated now when the cursor is hovering over it or when the menu is open. 
**Videos:**
Before:
https://github.com/user-attachments/assets/13f7ea04-c79d-4f81-8496-10bb568b28b7
https://github.com/user-attachments/assets/b171195b-e2ad-4f71-a2eb-464808719be4
After: 
https://github.com/user-attachments/assets/ed720839-5f25-47c7-bc47-6623f7e8961e …

fix: APPS-3395 make underline on menu only occur during hover and menu open

---

packages/vue-component-library/src/styles/ftva/_footer-links.scss
packages/vue-component-library/src/styles/ftva/_footer-primary.scss
packages/vue-component-library/src/styles/ftva/_footer-sock.scss

Connected to [APPS-3462](https://jira.library.ucla.edu/browse/APPS-3462)
**Component Updated:**
- _footer-links.scss
- _footer-primary.scss
- _footer-socks.scss
**Notes:**
- Updated scss variable syntax for max-width of FTVA footer components
**Preview Links:**
- https://deploy-preview-823--ucla-library-storybook.netlify.app/?path=/story/footer-links--ftva-style-links
- https://deploy-preview-823--ucla-library-storybook.netlify.app/?path=/story/footer-primary--ftva-footer
- https://deploy-preview-823--ucla-library-storybook.netlify.app/?path=/story/footer-sock--ftva-footer
-   [x] I checked that it is working locally in the FTVA-nuxt dev server
-   [x] I added a …

fix: APPS-3462 Correct FTVA Footer components variable syntax

---

.github/workflows/percy.yml
packages/vue-component-library/package.json
packages/vue-component-library/src/stories/NavBreadcrumb.stories.js
packages/vue-component-library/src/styles/default/_nav-breadcrumb.scss
packages/vue-component-library/src/styles/ftva/_nav-breadcrumb.scss
pnpm-lock.yaml

Connected to [APPS-3459](https://jira.library.ucla.edu/browse/APPS-3459)
**Component Updated:** NavBreadcrumb.vue
**Notes:**
- Fixed to include gray spacer icon (instead of default blue) for FTVA theme
- Fixed issue noticed on Nuxt level (Search Results and General Content templates) where if a breadcrumb's preceding parent is the root (home/search, home/about), an orphaned icon would appear as screen resolution decreases 
- Included additional stories to document root breadcrumb scenario
- Updated design tokens: 5.38.0 --> 5.44.0
<br><br>
From Desktop ...
<br>
To Mobile ... 
<br>
Fixed
**Checklist:**
-   [x] I checked that it is working locally in the …

fix: APPS-3459 Minor breadcrumb components update
